decaffeinate/decaffeinate

src/index.js, src/patchers/patchRest.js, src/utils/traverse.js, test/decaffeinate_test.js
Adds support for the `Rest` node.
=> Add support for rest params

src/patchers/patchStringInterpolation.js, src/utils/parse.js, src/utils/traverse.js, test/decaffeinate_test.js
=> New features (default params, MultiplyOp, NeqOp)

package.json
This makes it work when behind a proxy
=> Use https in package.json for git repository

src/utils/parse.js, test/in_test.js
First time contributing, so let me know if this is not the way to fix it :)
=> Fix in operator to work in compound expressions

src/utils/rangesOfComments.js, src/utils/trimmedNodeRange.js, test/decaffeinate_test.js, test/utils/rangesOfComments_test.js, test/utils/trimmedNodeRange_test.js
Not sure if this is the best way to fix. Would love to get feedback
=> Ensure that hashes in regexp are not treated as comments

src/index.js, src/patchers/patchObject.js, src/utils/parse.js, src/utils/types.js, test/object_test.js
@jeffchan @juliankrispel @nickdima You all have helped or offered to help. My plan is to start submitting new features as PRs. If something isn't clear, ask questions on the PR and I'll do what I can to improve the documentation/process as we go.
=> Ensure shorthand `this` object members are expanded correctly.

package.json, src/utils/determineIndent.js, src/utils/indentNode.js, test/parameter_assignment_test.js, test/utils/determineIndent_test.js
This still doesn't fix the sample file in #72 as there are further bugs with comment handling. More PRs forthcoming.
cc @jeffchan @juliankrispel @nickdima (let me know if you prefer not to be cc'd on these)
=> Fix indent detection

src/index.js, src/patchers/patchClass.js, src/patchers/patchFunctions.js, src/utils/shouldHaveTrailingSemicolon.js, src/utils/types.js, test/class_test.js
=> Transform static class methods.

src/utils/trimmedNodeRange.js, test/utils/trimmedNodeRange_test.js
Addresses #86.
This is quickly becoming a poor man’s CoffeeScript lexer. Hopefully this can be obviated by #65.
cc @jeffchan @netei
=> Fix trimming heregexes.

src/utils/trimmedNodeRange.js, test/string_test.js
=> Fix trimming ranges when triple-quoted strings are involved.

src/patchers/patchObject.js, test/decaffeinate_test.js, test/object_test.js, test/parameter_assignment_test.js
Fixes #91.
This gets us partway toward having more correctly-formatted objects. I included a comment in the new test that shows what it really should be.
=> Improve insertion of closing object braces.

src/index.js, src/utils/isExpressionResultUsed.js, src/utils/isImplicitlyReturned.js, src/utils/parse.js, src/utils/shouldHaveTrailingSemicolon.js, src/utils/types.js, test/implicit_return_test.js, test/utils/isImplicitlyReturned_test.js
=> Allow conditionals that become expressions to be treated as such properly.

src/index.js, src/patchers/patchBoolean.js, src/utils/types.js, test/boolean_test.js
=> Convert `on` and `off` to `true` and `false`.

src/utils/lex.js, src/utils/rangesOfComments.js, src/utils/trimmedNodeRange.js, test/string_interpolation_test.js
Closes #99.
I realize this just adds *even more* investment in our bespoke CoffeeScript lexer. I think it's probably a worthwhile addition if only because it unifies the two "lexers" we have into one.
=> Improve handling of special characters within triple-quoted strings.

src/patchers/DefaultParamPatcher.js, src/patchers/index.js, test/default_param_test.js
=> Add DefaultParamPatcher

src/patchers/UnaryExistsOpPatcher.js, src/patchers/index.js, test/unary_operator_test.js
Closes #126
First stab at this, many thanks to https://github.com/decaffeinate/decaffeinate/blob/master/CONTRIBUTING.md (very helpful)
Any feedback?
=> Add UnaryExistsOpPatcher

src/patchers/LogicalOpCompoundAssignOpPatcher.js, test/compound_assignment_test.js
Closes #130.
/cc @jeffchan @sandfox
=> Make logical compound assignment statements more natural.

package.json, src/stages/main/index.js, src/stages/main/patchers/SwitchCasePatcher.js, src/stages/main/patchers/SwitchPatcher.js, test/switch_test.js
This is a work in progress. There are still a few pending tests that need fixing.
=> Add support for `switch`

src/stages/main/index.js, src/stages/main/patchers/ExpOpPatcher.js, src/utils/traverse.js, test/math_test.js
=> Add support for exponentiation.

src/stages/main/index.js, src/stages/main/patchers/UnaryMathOpPatcher.js, src/stages/main/patchers/UnaryTypeofOpPatcher.js, test/unary_operator_test.js
This also fixes repeatability for other unary operators.
=> Add support for unary plus/minus.

package.json, src/stages/main/patchers/WhilePatcher.js, src/stages/normalize/index.js, src/stages/normalize/patchers/WhilePatcher.js, test/while_test.js
e.g. `a while b` or `while b then a`
=> Handle post-`while` and single-line `while` loops.

src/stages/main/patchers/BinaryOpPatcher.js, src/stages/main/patchers/InOpPatcher.js, src/stages/main/patchers/OfOpPatcher.js, src/stages/main/patchers/SeqOpPatcher.js, test/sequence_test.js
=> Add support for newline-separated sequence expressions.

package.json, src/utils/types.js, test/string_interpolation_test.js
Fixes decaffeinate/decaffeinate-parser#3.
=> Nested string interpolations

src/stages/main/index.js, src/stages/main/patchers/ForInPatcher.js, src/stages/main/patchers/ForOfPatcher.js, src/stages/main/patchers/ForPatcher.js, src/stages/normalize/index.js, src/stages/normalize/patchers/ForInPatcher.js, src/stages/normalize/patchers/ForOfPatcher.js, src/stages/normalize/patchers/ForPatcher.js, test/for_test.js
Doesn’t handle expressions or `for own` (#156, #157).
=> Add support for some `for` loops.

test/continue_test.js
=> Unskip `continue` test

src/stages/main/patchers/FunctionApplicationPatcher.js, test/function_call_test.js
=> Remove trailing commas from function calls.

package.json, test/mocha.opts
=> Added mocha.opts

test/conditional_test.js, test/decaffeinate_test.js, test/function_call_test.js
=> add some passed tests

src/stages/main/patchers/ProgramPatcher.js, test/continuation_test.js
=> Add support for continuations.

src/stages/normalize/index.js, src/stages/normalize/patchers/DefaultParamPatcher.js, src/stages/normalize/patchers/FunctionPatcher.js, src/stages/normalize/patchers/MemberAccessOpPatcher.js, test/class_test.js
support thinks like `constructor: (@a) ->`
=> Assign parameters to properties

package.json
Fixes an issue with a post if with parenthesized condition
=> Bump decaffeinate-parser.

package.json
=> fix: update add-variable-declaration to fix class method variables

.github/ISSUE_TEMPLATE.md
Does the instruction to uncomment the one you want make sense?
cc @alangpierce @Eden-Sun @an-sh @niieani @madskonradsen
=> chore: add a template for GitHub issues

script/update-website.sh
This was wrong and causing my PR builds to update the website.
=> chore: fix check for PR builds in Travis CI

src/stages/main/patchers/SlicePatcher.js, test/slice_test.js
This was causing some issues in my code where `@` wasn't being properly transformed to `this.`.
=> fix: patch the expression in slice operations

src/stages/main/patchers/BoundFunctionPatcher.js, test/function_test.js
=> fix: surround object initializers in arrow functions with parens

src/stages/main/patchers/TemplateLiteralPatcher.js, test/string_interpolation_test.js
=> fix: always use expressions within template literals

src/patchers/NodePatcher.js, test/function_call_test.js
Closes #412
Closes #410
Closes #405
Closes #379
Closes #370
Closes #276
The `appendLineAfter` method was careful to never insert code past the end of
the current node's "bounding patcher", but the bounding patcher was computed in
a way that didn't work in all cases; it just found the lowest enclosing node
that's surrounded by parens. So in `f(a, b)`, the bounding patcher for `b` is
the whole expression, so there's nothing to stop `b` from inserting code past
the end of the close-paren. To fix, I made the bounding patcher code a little
smarter to recognize when it's traversing up a function call node and stop
there.
=> fix: when patching an arg, don't write past the end of the call

src/stages/main/patchers/ConditionalPatcher.js, test/conditional_test.js
Fixes #470
The formatting isn't great, but it doesn't crash and generates correct code, so
it's certainly an improvement.
=> fix: handle conditionals with an else token but no alternate

src/stages/main/patchers/SlicePatcher.js, test/slice_test.js
=> fix: treat slice operands as expressions

src/stages/main/patchers/MemberAccessOpPatcher.js, test/member_access_test.js
=> fix: wrap number literals before a dot in parens

src/stages/main/patchers/ObjectBodyMemberPatcher.js, test/object_test.js
=> fix: remove parens if necessary when patching methods

src/stages/main/patchers/ForInPatcher.js, test/for_test.js
This commit does not use `for(;;)` when the loop has a dynamic range unless it also has an explicit step. That means `for [a..b]` will become a `for…of` loop. I added two skipped tests for turning them into `for(;;)` style, but it would require a fairly verbose loop header. However, that may still be better than requiring the `__range__` helper.
=> feat: use `for(;;)` style loops for some `for [a..b]` style loops

README.md, src/patchers/NodePatcher.js, src/patchers/types.js, src/stages/TransformCoffeeScriptStage.js
Progress toward #125
This isn't used yet, but it will be in a follow-up commit for the new
`--loose-default-params` option.
Also add a line to the README that I forgot to add earlier.
=> refactor: make options available to patchers

src/utils/stripSharedIndent.js
Progress toward #125
The original code tried to emulate CoffeeScript's herestring
whitespace-stripping rules, which have some bizarre edge cases, but that's not
needed anymore since coffee-lex is responsible for copying that behavior.
`stripSharedIndent` also had some bugs that I was running into in another
commit, where in some edge cases it would remove non-whitespace contents. Rather
than trying to directly fix those issues, I just rewrote the function in a way
that I think is simpler.
=> fix: rewrite stripSharedIndent to fix some correctness issues

package.json, test/chained_comparison_test.js, test/compound_assignment_test.js, test/conditional_test.js
This pulls in https://github.com/eventualbuddha/add-variable-declarations/pull/42
to fix some issues with variable scopes.
=> fix: update add-variable-declarations, fix tests

src/stages/main/patchers/ExistsOpPatcher.js, test/binary_operator_test.js
=> fix: properly patch operands in statement-style exists operators

src/patchers/NodePatcher.js, src/patchers/types.js, src/stages/main/patchers/ChainedComparisonOpPatcher.js, src/stages/main/patchers/DynamicMemberAccessOpPatcher.js, src/stages/main/patchers/ExistsOpPatcher.js, src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js, src/stages/main/patchers/MemberAccessOpPatcher.js, src/stages/main/patchers/ThisPatcher.js
Progress toward #592
I'm planning to add a new flag that says whether or not the repeat code needs
to be a valid assignee, so this should make that easier.
=> refactor: change makeRepeatable to take an object for options

src/stages/main/patchers/ForInPatcher.js, test/for_test.js
Fixes #640
Fixes #642
There were a number of details that weren't quite right in loop iteration, so I
reworked a lot of it:
* It's important to *always* use a C-style loop when iterating through a range,
since the final value of the loop assignee is meaningful in some cases. For
example, code might loop through `[0...length]` and then check if `i == length`
at the end to see if a break ever happened. This meant that I had to implement
the case where we need to decide at runtime which direction to iterate.
* Changing the end or the step of the iteration while the loop is in progress
should not affect the loop, so we need to save those values to variables at
the start. In the future, we could potentially do some fancy static analysis
to see if these variables could be assigned within the …
=> fix: rework many of the details of range iteration

package.json, src/stages/semicolons/index.js, test/return_test.js
=> fix: allow returning outside of a function

package.json
=> chore(package): add alangpierce as a contributor

src/stages/main/patchers/WhilePatcher.js, src/stages/normalize/patchers/LoopPatcher.js, test/while_test.js
=> fix: ensure inline loops work as expected

src/stages/main/index.js, src/stages/main/patchers/ModuloOpCompoundAssignOpPatcher.js, src/stages/main/patchers/ModuloOpPatcher.js, src/utils/registerModHelper.js, test/compound_assignment_test.js
Fixes #696
We already parsed this correctly, we just needed a new patcher type for it. I
also pulled out the helper itself into a shared util function.
=> feat: implement compound modulo assignment

src/patchers/SharedBlockPatcher.js, src/stages/main/patchers/BlockPatcher.js, src/stages/normalize/patchers/BlockPatcher.js, src/stages/normalize/patchers/FunctionPatcher.js
Fixes #196
This should be useful for a later commit that works with loops in the normalize
stage.
=> refactor: move some line insertion code into a shared BlockPatcher

src/stages/main/patchers/ForPatcher.js, test/soaked_test.js
=> fix: use patchAndGetCode when getting the target code in a loop

package.json, src/stages/main/patchers/ChainedComparisonOpPatcher.js, src/stages/main/patchers/EqualityPatcher.js, src/utils/getCompareOperator.ts, src/utils/traverse.js, test/chained_comparison_test.js
=> fix: correct behavior of some chained comparisons

src/stages/main/patchers/SwitchPatcher.js, test/switch_test.js
=> fix: call `setRequiresExpression` for the switch expression

package.json, src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js, test/soaked_test.js
Also update add-variable-declarations to latest.
=> fix: always patch the indexing expression in soaked dynamic member access

src/stages/main/index.js, src/stages/main/patchers/IncrementDecrementPatcher.js, test/unary_operator_test.js
=> fix: treat increment and decrement ops as non-repeatable

package.json
=> chore(package): update decaffeinate-parser to version 16.0.9

src/stages/normalize/index.js, src/stages/normalize/patchers/FunctionApplicationPatcher.js, test/soaked_test.js
=> fix: handle implicit soaked new operations

src/stages/main/patchers/ClassPatcher.js, test/class_test.js
=> fix: wrap class assignment expressions in parens when necessary

src/stages/main/patchers/SwitchCasePatcher.js, test/switch_test.js
=> fix: properly handle switch cases surrounded by parens

src/stages/main/patchers/CompoundAssignOpPatcher.js, src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js, src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js, src/stages/main/patchers/ModuloOpCompoundAssignOpPatcher.js, test/compound_assignment_test.js
=> fix: handle negation for all compound assign op cases

test/cli_test.js, test/fixtures/.gitignore, test/fixtures/A.coffee, test/fixtures/B.coffee.md, test/fixtures/C.litcoffee, test/fixtures/D.cjsx, test/fixtures/E
This makes the tests take a little longer, and the fixtures are a little
fragile, but it still seems important to test.
=> test: add tests for the CLI

src/stages/main/patchers/BlockPatcher.js, test/conditional_test.js, test/for_test.js, test/function_test.js
=> fix: avoid comma expressions when possible

package.json, src/stages/TransformCoffeeScriptStage.js, src/stages/main/patchers/InterpolatedPatcher.js, src/utils/traverse.js, test/string_interpolation_test.js
=> fix: add support for empty string interpolations

src/stages/main/index.js, src/stages/main/patchers/FloorDivideOpCompoundAssignOpPatcher.js, test/compound_assignment_test.js
=> feat: implement compound floor division assignment

src/stages/main/patchers/SlicePatcher.js, test/slice_test.js
=> fix: respect operator precedence in slice and splice operations

src/patchers/NodePatcher.js, src/stages/main/patchers/ForInPatcher.js, test/for_test.js
=> fix: don't use map and filter when the body or condition contain yield

package.json
=> fix(package): update add-variable-declarations to version 3.0.1

package.json, src/stages/main/patchers/ConditionalPatcher.js, src/stages/main/patchers/ForInPatcher.js, src/stages/main/patchers/ForOfPatcher.js, src/stages/main/patchers/ForPatcher.js, src/stages/main/patchers/LoopPatcher.js, src/stages/main/patchers/WhilePatcher.js, src/stages/normalize/patchers/ForPatcher.js, src/stages/normalize/patchers/LoopPatcher.js, src/stages/normalize/patchers/WhilePatcher.js, test/conditional_test.js, test/for_test.js, test/while_test.js
=> fix: properly handle empty bodies in loops and conditionals

src/stages/normalize/patchers/DefaultParamPatcher.js, test/default_param_test.js
=> fix: skip the defensive conversion for null default params

src/stages/main/patchers/AssignOpPatcher.js, test/function_call_test.js
=> fix: wrap assign seq ops in parens when used as arguments

README.md, src/cli.js, test/cli_test.js
=> feat: add a --loose option that enables all loose options

README.md, docs/conversion-guide.md, docs/suggestions.md
=> docs: reference suggestions docs, explain how to use JS modules

src/stages/main/patchers/ForInPatcher.js, src/stages/main/patchers/LoopPatcher.js, test/for_test.js
=> fix: properly handle expression loops with empty bodies

src/stages/main/index.js, src/stages/main/patchers/InOpPatcher.ts, src/stages/main/patchers/InterpolatedPatcher.ts, src/stages/main/patchers/ObjectBodyMemberPatcher.ts, src/stages/main/patchers/ObjectInitialiserMemberPatcher.ts, src/stages/main/patchers/ObjectInitialiserPatcher.ts, src/stages/main/patchers/QuasiPatcher.ts, src/stages/main/patchers/ReturnPatcher.ts, src/stages/main/patchers/SwitchCasePatcher.ts, src/stages/main/patchers/ThrowPatcher.ts, src/stages/main/patchers/TryPatcher.ts, src/stages/main/patchers/WhilePatcher.ts, src/stages/main/patchers/YieldReturnPatcher.ts
=> fix: move more patchers to TypeScript

src/stages/main/patchers/TryPatcher.ts, test/try_test.ts
=> fix: properly handle try/catch ending in `then`

src/cli.ts, test/cli_test.ts
add `-v` & `--version` options:
```
$ decaffeinate -v
decaffeinate v3.2.0
$ decaffeinate --version
decaffeinate v3.2.0
```
=> feat: add options to print current version

README.md
=> docs: mention the gitter room in the README

src/patchers/NodePatcher.ts, src/stages/main/patchers/BoundFunctionPatcher.ts, src/stages/main/patchers/ConstructorPatcher.ts, src/utils/blockStartsWithObjectInitialiser.ts, src/utils/containsDescendant.ts, src/utils/containsSuperCall.ts, src/utils/nodeContainsSoakOperation.ts, src/utils/normalizeListItem.ts, src/utils/referencesArguments.ts
Also consolidate various traversals that were similar or the same.
=> refactor: add a containsDescendant helper function

.travis.yml
=> Fix deploys

src/cli.ts
Looking at #1131 I decided to take another stab at doing async/await with the CLI functions. I opted to keep the `pending` queue and the specific functions in use to keep the refactoring simple. The biggest difference is that error handling is done at a higher level, in `processAll`.
=> Use async/await in CLI

src/stages/main/patchers/ObjectBodyMemberPatcher.ts, test/await_test.ts
=> fix: add `async` to async object and class methods

src/stages/main/patchers/AssignOpPatcher.ts, test/expansion_test.ts
=> fix: reorder complex assignment code so array elisions emit nothing

src/stages/normalize/patchers/ObjectInitialiserPatcher.ts, src/utils/postfixNodeNeedsOuterParens.ts, test/while_test.ts
=> fix: surround postfix loops in parens in an implicit object literal

package.json, src/stages/main/patchers/ObjectInitialiserMemberPatcher.ts, test/object_test.ts, yarn.lock
=> fix: handle computed shorthand properties

script/update-website.ts
I turned on email privacy in github for some reason, so I'm using my github noreply email instead.
=> chore(website): fix the script to update the website

package.json, test/import_test.ts, yarn.lock
See decaffeinate/decaffeinate-parser#411
=> fix: ensure imports without specifiers work

src/stages/main/index.ts, src/stages/main/patchers/ExportAllDeclarationPatcher.ts, src/stages/main/patchers/ExportBindingsDeclarationPatcher.ts, src/stages/main/patchers/ExportDefaultDeclarationPatcher.ts, src/stages/main/patchers/ImportDeclarationPatcher.ts, src/stages/main/patchers/ModuleSpecifierPatcher.ts, test/import_test.ts
=> fix: insert missing separators between module specifiers

package.json, test/import_test.ts, yarn.lock
=> fix: ensure `export { default } from './source'` works

package.json, test/declaration_test.ts, test/expansion_test.ts, test/for_test.ts, yarn.lock
=> fix: ensure assignment patterns have declarations as expected

src/stages/main/patchers/StringPatcher.ts, test/import_test.ts
=> fix: ensure import/export sources are not template literals

script/update-website.ts
It can be either `GITHUB_TOKEN` or `GH_TOKEN`.
=> chore(website): improve finding Github token

package.json, src/cli.ts, src/utils/Scope.ts, src/utils/debug.ts, test/support/validate.ts, yarn.lock
=> chore(package): update eslint to version 6.2.1

src/stages/main/patchers/ExistsOpPatcher.ts, src/stages/main/patchers/ForInPatcher.ts, test/for_test.ts
=> fix: ensure `for` targets with exists op work

src/stages/main/patchers/ExistsOpPatcher.ts, test/binary_operator_test.ts
=> fix: ensure exists op can be negated

src/utils/debug.ts
This makes a future version of `@typescript-eslint/eslint-plugin` happy.
=> style: add a comment to make the body non-empty

package.json, src/patchers/NodePatcher.ts, yarn.lock
No real changes required except that `delete`ing a property requires it be optional, i.e. that it can be undefined.
=> build: upgrade TypeScript

package.json, src/stages/main/index.ts, src/stages/main/patchers/DebuggerPatcher.ts, test/debugger_test.ts, yarn.lock
=> fix: add `debugger` support

src/stages/main/patchers/ConstructorPatcher.ts, test/class_test.ts
=> fix(class): bind after `super` in CS2

README.md, src/cli.ts, src/options.ts, src/stages/main/index.ts, src/stages/main/patchers/NullishCoalescingCompoundAssignOpPatcher.ts, test/logicalAssignment_test.ts
A minimal version of #2403 that excludes unrelated changes.
Closes #2403
=> Add logical assignment option

README.md, src/cli.ts, src/options.ts, src/stages/main/index.ts, src/stages/main/patchers/NullishCoalescingExistsOpPatcher.ts, test/nullishCoalescing_test.ts
Closes #2404
It's the same feature, but on a branch that is editable by me.
=> Add nullish coalescing option

package.json, pnpm-lock.yaml, test/comparison_test.ts
=> fix: update to `coffee-lex` with better CSX disambiguation

.github/workflows/ci.yml, .github/workflows/release.yml
- Use the latest versions of various actions.
- Use the built-in caching for `setup-node`.
- Use `corepack` to install `pnpm` in `release.yml`
- Use Node v18 in `release.yml` for `semantic-release` compatibility.
=> ci: update actions

.github/workflows/ci.yml, .github/workflows/release.yml
Should address the NodeJS v16 deprecation warnings.
=> ci: update actions versions
