decaffeinate/decaffeinate

src/index.js
test/decaffeinate_test.js

Because of the way we are doing string-replacement and not AST->AST transformation, we are quite sensitive to the order the transforms run.
In this case, if you rewrite the `->` and the `"#` first, the patcher can't find any original characters to target when it tries to insert the `return`.

Fix return of interpolated string

---

src/preprocessors/preprocessBinaryExistentialOperator.js
test/decaffeinate_test.js

As these test-cases show, there can be extra parentheses within the `ExistsOp` node that do not belong to either the left or right nodes. So it's not safer to rewrite the whole node.

Fix extra parens in binary existential preprocessor

---

src/patchers/patchConditional.js
test/decaffeinate_test.js

If you have a function that ends with a conditional, the close-of-function `})` can get written before the close-of-conditional `}`, due to the fact that functions trim trailing whitespace and conditionals do not.
This adds trimming to conditionals. It's possible that other block forms suffer the same bug and will also need to start trimming in case they appear at the end of a function.

trimNodeRange in conditionals

---

src/utils/parse.js
test/decaffeinate_test.js

This closes #26. Unlike the other three PRs I just filed, this one is kinda hacky. :stuck_out_tongue_winking_eye: 
I don't fully understand fixRange, other than to see that it's trying to patch over problems in coffeescript redux. But I can see that it is failing due to off-by-one-or-two errors, so this patches over the problem by doing a little search for the correct piece of original sourcecode.
This was a necessary bandaid so I could make progress for now. But others may also find it helpful.

Patch over buggy fixRange behavior

---

src/utils/types.js
test/binary_operator_test.js

Closes #72.
The offending code was `i - 27 & 7`. CoffeeScriptRedux has a bug where nested operators sometimes (always?) don't have proper ranges, so I had to whitelist some more node types as binary operators.
Note that the code in #72 still fails, but for a different reason. I'll submit a separate PR for that issue.
cc @jeffchan @juliankrispel @nickdima

Ensure bitwise operators have their ranges fixed properly.

---

src/patchers/patchComments.js
src/utils/rangesOfComments.js
test/comment_test.js
test/decaffeinate_test.js

This changes the behavior of block comments such that leading hash marks no longer mark a comment as being a documentation comment. Instead, all block comments are treated equally and users wishing to make a block comment a doc comment simply add an asterisk after the initial `###`.

Unify block & doc comments.

---

src/utils/trimmedNodeRange.js
test/utils/trimmedNodeRange_test.js

Mostly this ensures we insert semicolons (or newlines etc) at the right positions, essentially anywhere we would try to trim the node range.
Closes #84.
cc @jeffchan @alexgorbatchev

Ensure we handle escape characters when processing strings/regexes.

---

package.json

For some reason specifying the full URL fails (npm 2.5.1). Using the NPM-blessed short-syntax works.
```
$ npm install -g decaffeinate
npm ERR! fetch failed https://github.com/michaelficarra/CoffeeScriptRedux.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```
More details:
https://github.com/npm/npm/issues/7708

Fix installation issue

---

package.json
src/index.js
src/stages/esnext/index.js
test/binary_operator_test.js
test/chained_comparison_test.js
test/class_test.js
test/compound_assignment_test.js
test/conditional_test.js
test/decaffeinate_test.js
test/declaration_test.js
test/function_call_test.js
test/function_test.js
test/implicit_return_test.js
test/javascript_test.js
test/prototype_member_access_test.js
test/regular_expression_test.js
test/return_test.js
test/semicolon_test.js
test/shorthand_this_test.js
test/string_interpolation_test.js
test/string_test.js
test/switch_test.js
test/unary_operator_test.js

This upgrades the resulting code to use even more modern features, such as `let`.

Add esnext as the final transformation stage.

---

CONTRIBUTING.md
src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/FloorDivideOpPatcher.js
src/stages/main/patchers/UnaryOpPatcher.js
test/conditional_test.js

Ensure conditional-as-ternary has parens if needed.

---

CONTRIBUTING.md
src/patchers/NodePatcher.js
src/stages/main/patchers/BoolPatcher.js
src/stages/main/patchers/ThisPatcher.js
test/function_call_test.js

Introduces `getOriginalSource` and `getPatchedSource`. The reason the original code failed is that we might have replaced up to the start of the node, and magic string does not allow slicing using the end of an edited range as a slice anchor.
Fixes #150.

Fix patching booleans in some contexts.

---

src/patchers/NodePatcher.js
src/utils/PatchError.js

Inspired by #150 since the error occurs on a large file and it isn’t obvious what caused it.

Pinpoint nodes causing errors.

---

package.json
src/patchers/NodePatcher.js
src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
src/utils/Scope.js
test/compound_assignment_test.js

- `or=` was being interpreted as two tokens, `or` and `=`
- `or=` wasn’t identified as needing to negate its condition
- logical op compound assignments didn’t patch their expressions

Fix logical compound assignments

---

.eslintrc
eslint-rules/index.js
eslint-rules/package.json
package.json

as rulesdir is deprecated: eslint/eslint#2715
this has the sideeffect that you can run eslint without commandline options

Converted ESLint rules into a plugin

---

src/patchers/NodePatcher.js
test/conditional_test.js

current implementation assumes "surrounded", when it starts with a left and ends with a right parenthese, which is false positiv in case of `(a) and (b)`

fix isSurroundedByParentheses

---

src/stages/main/patchers/FunctionApplicationPatcher.js
src/stages/main/patchers/NewOpPatcher.js
test/new_op_test.js

This ensures they're always patched the same way. Fixes #198.

Bring `NewOpPatcher` in line with `FunctionApplicationPatcher`.

---

src/stages/main/patchers/ObjectInitialiserPatcher.js
test/object_test.js

Some code that I've been attempting to convert to es6 does some fairly odd looking things with parens. However, it is valid CoffeeScript and when compiled to JavaScript "does the right thing".
For example:
```
someFunction = ->
return (
a: b
b: c
)
```
Compiles to:
```
var someFunction;
someFunction = function() {
return {
a: b,
b: c
};
};
```
In decaffeinate this currently results in an error raised in the ObjectInitialiserPatcher:
```
NormalizeStage someFunction = ->
return (
a: b
b: c
)
MainStage someFunction = ->
return (
a: b
b: c
)
FunctionPatcher INSERT 15 "function" BEFORE "->\n    r"
FunctionPatcher INSERT 15 "() " BEFORE "->\n    r"
FunctionPatcher OVERWRITE [15, 17) "->" → "{"
ObjectInitialiserPatcher INSERT 30 "{\n        " BEFORE "\n       "
ObjectInitialiserPatcher INSERT 29 …
```

Handle implicit objects wrapped in parens

---

src/patchers/NodePatcher.js
src/stages/main/patchers/WhilePatcher.js
test/function_call_test.js
test/while_test.js

This fixes various things that behave differently based on their surrounding parentheses. Fixes #261. It also causes some things, such as `while` expressions, to be formatted differently. It's not quite as pretty, but I think it's an okay compromise.

fix: treat call_start & call_end tokens as parentheses

---

src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/InOpPatcher.js
src/stages/main/patchers/LogicalOpPatcher.js
test/binary_operator_test.js
test/in_test.js

CoffeeScript converts `a in [b, c]` to `a === b || a === c` rather than using `indexOf` on the array. This follows suit and handles negation better than CoffeeScript.

Better `in` handling

---

src/index.js
src/patchers/NodePatcher.js
src/stages/TransformCoffeeScriptStage.js
src/utils/PatchError.js

This is still sort of work-in-progress in that it copies `lineColumnMapper` from
`decaffeinate-parser`, so let me know if you think it would be better to change
`decaffeinate-parser` first to expose that function (or some other approach).
This is originally based on https://github.com/decaffeinate/decaffeinate/pull/222 ,
but I ended up changing the approach pretty significantly.
Since the `PatchError` class already contains logic to pretty-print an error in
a particular place in a file, with necessary context, I decided to reuse that.
Unfortunately, it relied on having a `ParseContext` from `decaffeinate-parser`,
even though none of the code is CoffeeScript-specific. The main purpose of the
`ParseContext` over just the source code is for the `lineMap`, so for now I
refactored `PatchError` …

Improve error reporting when there is a parser error

---

src/stages/main/patchers/FunctionApplicationPatcher.js
test/function_call_test.js

Fixes #266.
In ac594494dfecc1bc907add06ea32df4801b61013 , some of the logic was changed so
that function call parens are treated as normal parens, at least in more cases.
This was confusing some existing logic that tried to remove any trailing commas
in function arguments. In a case like `a(b(c), d)`, the transformation code
would start from the end of the `c` expression, move until the next token, see
if it's a comma, and if so, remove it. But after changing the interpretation of
parens, the end of the `c` expression is now the close-paren, so it finds a
comma outside of the argument list and removes it.
To fix this issue, we can just add an additional check that the found comma is
actually within the function call, so the logic is now "move until the next
token to see if it's a comma, …

Don't remove trailing commas that are past the end of the function call

---

src/index.js

Step 1 of 2 for #278.
This is useful so that the repl can call `PatchError.prettyPrint` on errors thrown
by `convert`.
This is the best I could come up with to both import `PatchError` for use in
`index.js` and also export it from `index.js`. If there's a way to do it that doesn't
involve typing `./utils/PatchError.js` twice, I'm happy to go with that.

Expose the PatchError class as a decaffeinate export

---

src/utils/PatchError.js
test/utils/PatchError_test.js

The code was using `isNaN` to determine if the line/column pair was valid, but
`isNaN(null)` is `false` in JS, so this was always returning false. This caused
the repl to sometimes not display the last line in the error, e.g.:
http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=a%3F.b

Fix PatchError.prettyPrint when the file doesn't end in a newline

---

src/stages/main/patchers/ReturnPatcher.js
test/return_test.js

This comes up, for example, when doing `return if ...`.
Closes #271.

fix: always use an expression as the argument to a return statement

---

src/stages/main/patchers/BlockPatcher.js
test/class_test.js
test/function_test.js
test/return_test.js

The NormalizeStage sometimes adds them to prevent inserted statements from being implicitly returned unintentionally. This has the side effect of stripping empty trailing return statements that were in the original source code, but those were probably also there to prevent an implicit return and so would not normally be in the JavaScript version of the code anyway.
Closes #193.

feat: strip trailing `return` statements without an argument

---

css/main.css
repl/index.html
scripts/repl.js

Fixes the issue mentioned in #285
The demo-code is kept in a hidden text-field until it is decided whether or not it should be used as it seemed like the most sane solution.

fix: only add demo-code in case of no query-string or localstate is present

---

src/index.js

The code I added to catch ParseErrors from JS code was using (`pos`, `pos + 1`) as
the range, but if the position was at the very end of the string (e.g. due to
unbalanced parens), it would cause a crash because the end position would be
null. To fix, I changed it to instead just use the last character in the code in
that case rather than one after the last.

fix: don't pretty-print with out-of-range indexes

---

src/stages/main/patchers/BlockPatcher.js
test/return_test.js

Before this commit, the comment after a removed return statement would be
destroyed:
http://decaffeinate-project.org/repl/#?evaluate=true&code=-%3E%0A%20%20a%20%20%23%20foo%0A%20%20return
Now, the code is a little more careful by deleting up to the start of the line
or the previous semicolon. Also, the code now exits early and doesn't patch the
`return` node or insert a semicolon at the end, since that was causing a
semicolon at the end of the comment.
This also fixes a crash on this type of input that I ran into when using
magic-string with  https://github.com/Rich-Harris/magic-string/pull/89 applied.

fix: don't remove comments when removing trailing empty returns

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

The problem was that the code was inserting tokens out of order, which was
confusing magic-string. Here's what the old code did:
* Wrap the loop body in an `if` statement for the filter:
* Prepend `if (c) {` to the start of the loop body.
* Append `}` to the end of the loop body.
* Patch the loop body. Among other things, this appended `)` to the end because
the loop body ended in an implicit function call.
So, from magic-string's perspective, the index at the end of the loop body had a
`}` appended, then a `)` appended, which is wrong. To fix, I reworked the
function to prepend the text, then patch, then append the curly-brace. I also had
to manually create the closing curly brace for the loop since I was appending
code after `patch` finished. All of this complexity only happens when …

fix: handle for...when loops ending in implicit function calls

---

src/patchers/NodePatcher.js
src/stages/main/patchers/FunctionApplicationPatcher.js
src/stages/normalize/index.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/conditional_test.js
test/for_test.js
test/function_test.js
test/object_test.js

The code in #301 is actually parsed incorrectly by the CoffeeScript parser (even
before decaffeinate-parser does anything interesting). It says that the function
body ends at the end of the file, so decaffeinate was inserting a
close-curly-brace at the end of the file, which was incorrect. However, the
function application was correctly parsed, and explicitly putting parens for the
function application causes the CoffeeScript parser to work again, so we can
work around this issue by inserting parens for all implicit functions before the
MainStage.
I think this will also fix a bunch of other problems caused by implicit function
calls. For example, it also happens to fix #269. In the codebase that I'm trying
to decaffeinate, it fixes 49 out of the 104 files with decaffeinate failures
that I …

fix: add implicit function call parens in the normalize step

---

src/stages/main/index.js
src/stages/main/patchers/ModuloOpPatcher.js
src/utils/traverse.js
src/utils/types.js
test/binary_operator_test.js

As suggested in #303, this works by registring a function, `__mod__`, that behaves
like the `%%` operator. I based the code off of `InOpPatcher`.
Closes #303.

feat: add support for ModuloOp

---

src/stages/main/index.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ExpansionPatcher.js
src/utils/Scope.js
src/utils/traverse.js
test/expansion_test.js

This is a partial implementation of expansions, which handles them for array
assignment and destructuring, but not for function parameters or nested within
more complicated assignments. For those unsupported cases, I throw an error
linking to #268 when the expansion node is traversed.
Currently the only special case is `[a, b, ...]`. Every other case just turns
into a series of assignments that do array lookups.

feat: handle expansions in array assignment

---

src/stages/normalize/patchers/ConditionalPatcher.js
test/conditional_test.js

The ConditionalPatcher code had a mistake where it was skipping the else case.
Now that implicit function call parens are added in the normalize stage, this
was causing some errors where parens wouldn't get added.

fix: traverse into "else" cases in the normalize stage

---

src/patchers/NodePatcher.js
src/patchers/types.js
src/stages/normalize/patchers/ConditionalPatcher.js
test/conditional_test.js

Uses `move` instead of overwriting the whole node, which works better with magic-string.
Fixes #327.

fix: ensure implicit functions as conditions in post-IF works

---

package.json

fix: make shorthand-candidate properties work with nothing around the colon

---

src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js
test/support/validate.js

Partial fix for #156.
This commit handles "for in" using the strategy of transforming it to
`a.filter(...).map(...)`. This works in the most common cases, but there are some
edge cases that it doesn't handle (where I throw an error):
* Loop expressions using a `by` clause.
* Loop expressions where the body cannot be patched as an expression. In
particular, I don't think there's a great way to handle `break`, `continue`,
and `return` within loop expressions using `map` and a lambda.
* Expressions that use a filter and also assign the index to a variable. In this
case, the code would be incorrect, because the filter step changes the size of
the array and thus the indexes.
This technically could change behavior when looping over array-like objects,
like `{length: 2, "0": "hello", "1", …

feat: handle some "for in" loop expressions using filter and map

---

src/stages/main/index.js
src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js
src/stages/main/patchers/SoakedFunctionApplicationPatcher.js
src/utils/findSoakContainer.js
test/soaked_test.js

This is a first pass that I think should correctly handle nearly every case for
all soak operations. For now, the generated JavaScript always uses a helper
function, but in the future it probably makes sense to do something
simpler/shorter when we can get away with it.
Some details:
* In order to handle chained soaked operations, like `a?.b.c = d()`, I walk up
the AST and stop when I get to the last soak-friendly node. That node's start
and end define the "soak range" for the `__guard__` function.
* To handle nested soaks correctly, we also stop traversing up if we hit another
soak operation.
* Since function application soaks have a different condition (they only pass if
left side is really a function), I had to make a separate `__guardFunc__`
helper for that case.
* I named the …

feat: implement soaked member access, dynamic member access, and function application

---

package.json

browserify is no longer needed in this repo since now the decaffeinate-project.org repo does the browser build.

chore: remove browserify

---

src/patchers/NodePatcher.js
src/stages/main/patchers/BoundFunctionPatcher.js
src/stages/main/patchers/ForInPatcher.js
src/utils/isObjectInitialiserBlock.js
test/for_test.js

Just like when creating arrow functions in `BoundFunctionPatcher`, we need to
put parens around the body if it's just an object literal so that JS can parse
it correctly.

fix: allow for-in expressions with an object literal body

---

src/stages/main/patchers/DynamicMemberAccessOpPatcher.js
test/member_access_test.js

This was breaking code like `a[if b then c else d]`.

fix: force dynamic member access indices to be expressions

---

src/patchers/NodePatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/array_test.js
test/function_call_test.js

This fixes a crash where a close-paren was being placed in the wrong place.
[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=%5Ba(b%2C%20c%20%7B%0A%7D)%5D)
The previous code was using `appendLineAfter`, which was using
`getBoundingPatcher` as a way of determining where it's safe to place the
paren. However, `getBoundingPatcher` doesn't seem to always do that, for example
when the node is an argument to a function taking multiple arguments. Instead, I
now just always place the close-paren in the function call's `innerEnd`. Also,
when deciding whether to put the close-paren on a new line or right after the
end of the call, I now put it right at the end if the call ends with a `}` or a
`]`, which fixes a bunch of ugly newlines that I was seeing.
Unfortunately, this causes a …

fix: improve the pacement of the close-paren for implicit function calls

---

src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

Previously, it would leave the `when` clause alone, resulting in invalid JS.
Now, it uses the same strategy that for-in loops use: after handling any initial
assignment, wrap the normal body in an `if` statement.
Also, `ForPatcher.patchAsStatement` was unused (both `ForInPatcher` and
`ForOfPatcher` explicitly override it and never use super), so I just removed
it.

fix: handle for-of statements with a filter

---

src/index.js
src/utils/formatCoffeeLexTokens.js
src/utils/formatCoffeeScriptAst.js
src/utils/formatDecaffeinateParserAst.js
src/utils/formatRange.js
test/utils/formatCoffeeLexTokens_test.js
test/utils/formatCoffeeScriptAst_test.js
test/utils/formatDecaffeinateParserAst_test.js

This is the decaffeinate side of a change to the repl that makes it possible to
run some but not all stages of decaffeinate and inspect the intermediate
results. In addition to supporting the normal stages, I also allow inspecting
the results produced by the CoffeeScript parser, coffee-lex, and
decaffeinate-parser. In all three of these cases, there wasn't (to my knowledge)
an existing nice way of printing out these formats, so I wrote pretty-printers
for each of them, which use a consistent format for naming positions in code.
There are certainly some similarities between the pretty-printers, but there are
enough differences that it seems best to keep the code mostly separate.
The main use case here is to make it easier to figure out what went wrong when
decaffeinate crashes, e.g. …

feat: add a `runToStage` option so decaffeinate can return intermediate results

---

src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

We can just use a JS for-of loop on `Object.keys`, which is defined to iterate
through the own properties in the same order that JS for-in would.
Closes #157.

feat: implement "for own" in a statement context

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/class_test.js
test/super_test.js

fix: always spread `arguments` in `super` call with implicit args

---

src/index.js
src/utils/formatCoffeeScriptAst.js
src/utils/formatCoffeeScriptLexerTokens.js
src/utils/formatCoffeeScriptLocationData.js
test/function_call_test.js
test/utils/formatCoffeeScriptLexerTokens_test.js

The last CoffeeScript bug was a lexer issue, and it looks like there's another
lexer bug, so it seems nice to be able to look at the location data of each
token produced by the CoffeeScript lexer.
[Live demo](http://www.alangpierce.com/decaffeinate-project.org/repl/#?evaluate=true&stage=coffeescript-lexer&code=SomeArr%20%3D%20%5B%20-%3E%0A%20%20if%20something%0A%20%20%20%20lol%20%3D%0A%20%20%20%20%20%20count%3A%207%0A%5D)
Also sneak in a regression test for #356, since I never got to that earlier.

feat: add a "CoffeeScript lexer" intermediate stage for the repl

---

src/utils/PatchError.js
test/utils/PatchError_test.js

fix: don't crash when formatting an error with an invalid range

---

src/patchers/NodePatcher.js
src/stages/normalize/index.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/function_call_test.js

This was a matter of changing the normalize stage to included soaked function
calls for `FunctionApplicationPatcher`, then updating the logic to be more
careful about the possibility of a `?` between the function and the args.
Closes #382.

fix: handle soaked implicit function calls

---

src/patchers/NodePatcher.js
src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/WhilePatcher.js
test/while_test.js

Progress toward #156.
The existing while loop IIFE code was trying to cram all of the generated code
on one line, which looked kind of bad in longer cases. Since I'm going to be
extending this code to all types of loops soon, I figured it would be good to
improve the formatting first.
The new rule is that if a loop is formatted within an IIFE, we never treat it
as an inline node. To help support this type of case, I added a `setIndent`
method that forces the indentation level to a certain value, which helps ensure
that the generated code is nicely nested regardless of the details of how the
original code was formatted.
Unfortunately, the new indentation caused some excessive whitespace in some
`yield` examples, and there are some cases where newlines in the original
CoffeeScript cause …

fix: improve formatting in IIFE-style while loop expressions

---

src/stages/normalize/index.js
src/stages/normalize/patchers/BlockPatcher.js
src/utils/getIndent.js
src/utils/getStartOfLine.js
test/indentation_test.js

The paren-adding step of NormalizeStage can sometimes create invalid
CoffeeScript because CoffeeScript is more strict about indentation in some cases
than others. This adds a step to NormalizeStage that ensures that all statements
within blocks have the same indentation level, which should avoid this error.
Closes #394.

fix: allow valid inconsistent indentation

---

src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/ForPatcher.js
src/stages/main/patchers/LoopPatcher.js
src/stages/main/patchers/WhilePatcher.js
test/for_test.js
test/while_test.js

This changes `for` loops used as expressions to use a statement-style loop
within an IIFE, unless we already have a better way to transform the expression.
Conceptually, this was fairly easy since we already do this type of thing for
`while` loops, so it was mostly a matter of pulling that logic into a shared
`LoopPatcher` class. However, getting the formatting right in all cases ended up
being a huge pain, so I ended up reworking how a lot of that stuff works.
There are two main things that I introduced:
* All styles of loops now use common terminology for three indentation levels:
the top-level loop where the `for` or `while` goes, the first level of the
loop body, where we often generate an assignment statement, and the "main"
loop body, which might be indented one more level to be …

feat: add support for all for loops used as expressions

---

src/index.js
src/utils/resolveToPatchError.js
test/utils/resolveToPatchError_test.js

Fixes #413.
This is particularly useful for cases where the NormalizeStage generates invalid
code, but also helps for actual invalid CoffeeScript.
Since we handle two kinds of errors, I moved that code into a separate tested
area where we can add additional error conversion as it comes up.
Demo: http://www.alangpierce.com/decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%7B%0A%20%20a%3A%20-%3E%0A%20%20%20%20return%20b%20c%2C%0A%20%20%20%20%20%20d%20e%2C%0A%20%20%20%20%20%20%20%20f%0A%20%20%20%20%20%20g%20h%2C%20i%2C%0A%7D

fix: show context information for coffeescript parse errors

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/function_call_test.js
test/new_op_test.js

Fixes #391.
The expression `new A().B` was being parsed as `new (A().B)`, so decaffeinate
was treating it as a parens-less constructor invocation and adding parens. In
reality, the behavior in both JavaScript and CoffeeScript is `(new A()).B`, so
it's incorrect to add parentheses.
Unfortunately, it looks like the underlying cause here is a CoffeeScript parser
bug. It seems to parse it as `new (A().B)` ([repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=coffeescript-parser&code=new%20A().B)),
so decaffeinate sees zero arguments and no parens and assumes that the extra
parens are necessary.
To fix, I just removed the paren-adding from decaffeinate on constructor
invocations with no args. It's still correct in JavaScript to call a
constructor without parens, so the generated …

fix: don't add incorrect parens for new expressions

---

src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
test/compound_assignment_test.js

Closes #423.
CoffeeScript allows things like `or =` and `|| =` and treats them as compound
assignments (even though in general it doesn't allow spaces in operators; for
example, `? =` is NOT a valid assignment operator). Our check wasn't handling
that case, so `isOrOp` was returning `false` and the assignment was being
treated as a logical AND. To fix, I just looked at the start of the operator
rather than the whole operator.

fix: allow a space in logical OR assignments

---

src/stages/normalize/patchers/DefaultParamPatcher.js
src/stages/normalize/patchers/MemberAccessOpPatcher.js
test/class_test.js

Fixes #232.
The code for handling `@` in params already had a check to make sure it doesn't
traverse up the right side of a default param assignment (otherwise `(a = @b) ->`
would get converted incorrectly), but it also skipped the valid case where we
traversed up the left side. To fix, I just needed to see which of the parent's
children the current patcher is when traversing up.

fix: allow parameter property assignments with defaults

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/NegatableBinaryOpPatcher.js
test/conditional_test.js
test/instanceof_test.js

Closes #434.
For many binary operators (including assignment operators), the previous behavior
of just prepending `!` for negation wasn't correct; we need to add parens in
some cases. For simplicity, I made it so we add parens in ALL cases, even if
parens already exist. I also made it add the `!` at `innerStart` rather than
`outerStart`, since otherwise I was seeing some cases like `if !(a = b)` in the
generated JS, which doesn't work. In general, it seems safest to avoid writing
code outside an expression's enclosing parens as much as possible.
I also fixed a related issue in `NegatableBinaryOpPatcher`.
Since the [no-extra-parens](http://eslint.org/docs/rules/no-extra-parens) eslint
rule has an auto-fixer, it's probably reasonable to care a bit less about
generating unnecessary parens …

fix: handle `unless` with binary operator conditions

---

src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
test/compound_assignment_test.js

Closes #439.
Looks like this was just added by mistake at one point, and in simple cases it
doesn't matter, but when patching functions it was causing strange results.

fix: don't double-patch the right side of a compound logical assignment

---

src/stages/normalize/index.js
src/stages/normalize/patchers/MemberAccessOpPatcher.js
src/stages/normalize/patchers/ObjectInitialiserMemberPatcher.js
test/class_test.js

Closes #213.
In a case like `{@a}`, the decaffeinate-parser AST uses the same node for the
key and the value, so while searching for this-assignment nodes we were seeing
`@a` twice (even though conceptually it might be better represented as `{a: @a}`
in the AST, but that causes problems elsewhere). This meant we were adding two
assignment statements when we should have been adding one. There was already a
mechanism to ignore some nodes in parameter bodies (used to ignore usages of `@`
within parameter defaults), so this issue can be fixed by just ignoring object
keys, which always just say the name of the field to be extracted rather than
having any effect on the assignments that are done.

fix: correctly handle destructure parameters with property assignments

---

test/conditional_test.js

Now that magic-string has been updated, the test works.

test: enable a test that was disabled waiting on another PR to land

---

src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Closes #388.
When an `if` expression is complicated enough, we can't reasonable turn it into
a ternary; it's cleaner (and sometimes necessary) to use an IIFE instead.
We already have IIFE code working for loops, so this borrows most of the
implementation details from that.
I didn't focus as much on formatting as for the loop case, so it's certainly
possible that there are some situations where the indentation looks wrong, but
in the few examples I tried it looks pretty good. If there are formatting
problems, those can be fixed as lower-priority follow-up issues.
I also made it so we require both the consequent and the alternate (if present)
to be patchable as an expression before we say that the condition can be a
ternary; otherwise we would sometimes attempt a ternary patch that would …

feat: implement IIFE-style conditionals

---

src/stages/main/patchers/FunctionPatcher.js
test/function_call_test.js
test/function_test.js

Closes #451.
There was already a special case that when a function expression is surrounded
by parens, the `}` is placed immediately before the close-paren. This also
worked for single-argument function invocations, but in a multi-argument
function invocation, neither argument is considered to be surrounded by parens,
so it wasn't doing anything smart. To fix, I added a new special case: if a
function expression is the last argument to a function, place the `}` just
before the CALL_END token.

fix: improve formatting when a function is the last argument to a function

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

Closes #467.
This was a magic string issue where inserts were happening out of order. Now,
when patching expression-style for-in loops, we patch the body in the middle,
and split the `surroundInParens` call into an insert before and after. Placing
the open-paren in a consistent way ended up being tricky, and required some
cases to handle both the inline and multiline cases.

fix: properly convert for expressions with implicit object bodies

---

src/stages/main/patchers/ConditionalPatcher.js
src/stages/normalize/patchers/ConditionalPatcher.js
test/conditional_test.js

Closes #305.
This was basically just a matter of going through ConditionalPatcher in both the
normalize stage and the main stage and making sure they account for the case
where `consequent` is null. There are some regions of code that only happen when
`consequent` is non-null, like post-`if` patching and code with a `then` token,
so I left those as-is.
The formatting is a little weird for a missing consequent when the conditional
is used in an expression context, but that's probably a rare case and can be
cleaned up later.

fix: properly handle conditionals with a null consequent

---

src/patchers/NodePatcher.js
test/switch_test.js

Closes #448.
The switch patcher was using `appendToEndOfLine`, which was just writing to the
end of the current line, even if it was past the end of the expression (in this
case, it was writing past the close-paren for the function call). To fix, I just
made `appendToEndOfLine` include the same logic as `appendLineAfter`: write to
the right place if possible, but not past the bounding patcher.

fix: respect bounds when writing the end of a switch expression

---

src/stages/main/patchers/MemberAccessOpPatcher.js
src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js
src/stages/main/patchers/SoakedFunctionApplicationPatcher.js
src/stages/main/patchers/SoakedMemberAccessOpPatcher.js
src/utils/findSoakContainer.js
test/soaked_test.js

Closes #462.
This fixes the JS output for code like `a().b?()` and `a()[b()]?()`, where the
`this` value needs to be set properly for the function call. The solution is
among the same lines as `__guard__`/`__guardFunc__`, but even uglier. Rather
than using a function to eager-evaluate the base and optionally call a lambda,
we eagerly evaluate both the object and the method name and then optionally pass
both into the lambda. There were also some details in handling cases like
`@a?()`, `a?.b?()`, and `a?.b.c?()`.
As before, this (mostly) handles the crazy cases, and #336 is the task for making
the output nicer in the non-crazy cases. In the meantime, I always just manually
fix up the generated JS code to never use `__guard__`-type things.
One decision I made is that I treat `a.b?()` as …

fix: correctly pass `this` in soaked function applications

---

src/stages/main/patchers/SwitchCasePatcher.js
test/switch_test.js

Closes #340
This was just a matter of going through `SwitchCasePatcher` and handling the
case where `consequent` is null.

fix: allow empty switch cases

---

src/stages/main/patchers/IdentifierPatcher.js
src/stages/main/patchers/LoopPatcher.js
test/for_test.js

Fixes #473
`break` and `continue` were parsed as regular identifiers, so the loop
expression patching code would sometimes make a lambda trying to return them or
generated code like `result.push(break)`. Probably the cleanest fix would be to
parse `break` and `continue` differently in the AST, but the easy fix is to just
say that the identifier can't be patched as an expression in those cases, and
handle that properly.

fix: properly handle break and continue in loop expressions

---

src/stages/normalize/patchers/ConditionalPatcher.js
test/function_call_test.js

Closes #479.
Closes #459.
Closes #419.
Closes #378.
Closes #334.
The post-if patcher was changed to use `move` in magic-string, but that ended up
messing with the order that things were written in. Now that magic-string
properly handles `remove`, it should be safe to go back to using `insert`, with
the general strategy being to insert fragments in order in the source code
whenever possible.

fix: change post-if patching to use insert

---

src/stages/normalize/index.js
src/stages/normalize/patchers/AssignOpPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
src/stages/normalize/patchers/ProgramPatcher.js
test/class_test.js

Closes #397. See that issue for a much more thorough description of the strategy
here. This change doesn't handle all cases described in that issue (in
particular, it doesn't support arbitrary code within classes that are used in an
expression context), but it handles enough cases to support all classes in the
codebase I'm working with.
Since this transform significantly rearranges classes, I decided to do it as a
CS->CS transform in the normalize stage. That should hopefully avoid weird
magic-string issues in the main stage.
This approach is maybe a bit controversial in that it changes the implementation
for class fields to use prototype properties. In my case, putting class
properties on the prototype is necessary to avoid widespread correctness issues
in my codebase. (See …

feat: allow code within class bodies

---

src/stages/main/patchers/ForPatcher.js
test/for_test.js

Fixes #483.
Since the condition in a loop is already going to be surrounded by parens,
there's no need to add an extra set of parens. Also, it was causing a bug where
one of the parens was kept but the other one wasn't.
This doesn't really solve the general case; ideally there would be a way to get
the expression including the parens.

fix: don't include parens when patching loop filters

---

src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Closes #492.
The close-brace and the end of the consequent statement were having code
inserted at the same index, so we need to make sure the patching happens in the
order that they should appear in the code.

fix: patch code in order in conditional consequents

---

src/stages/main/patchers/SwitchPatcher.js
test/switch_test.js

Fixes #494.
Fixes #319.
The code was inserting the first part at `outerStart`, which is before the
enclosing left-paren, which is wrong. Instead, it should use `contentStart`.

fix: properly position the first part of switch IIFE patching

---

src/stages/main/patchers/ForInPatcher.js
test/continue_test.js
test/for_test.js

Closes #323
Technically for-of loops use the JS iterator protocol insead of CoffeeScript's
notion of an array-like object, but that's also true for things like
destructuring. Some of this code was based on the code from `ForOfPatcher`,
since that's similar in that it just changes `of` to `in` in simple cases.

feat: convert CS for-in to JS for-of when possible

---

docs/conversion-guide.md
src/stages/main/patchers/InOpPatcher.js
test/function_call_test.js
test/in_test.js

Closes #363
Note that this means that anyone using decaffeinate needs to be in an
environment supporting ES2016. I updated the docs to include this.

feat: use `.includes` instead of a helper method for `in`

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

Fixes #491.
This fixes an issue where an overwrite operation would interfere with an earlier
patch. This can be fixed by being more careful about patching order: generally
all patching should happen in order in the code rather than jumping around.

fix: change map/filter patching to go in order

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

Fixes #498
Previously, you might call `patch` on a sub-patcher, then use `slice` to get the
generated code, but this didn't always work out well, since we always do
`insertLeft` (for magic-string sanity), so slice would sometimes miss an
open-paren inserted at the start.
This commit changes the loop filter case to use this new method, but probably
other code paths should be moved over to it as well in the future.

fix: improve the process of patching code for use elsewhere

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

Fixes #265
There can still be a catch or finally case without a catch or finally body, so
we need to be a little smarter about searching for the token and handling the
different cases.

fix: handle try/catch with empty catch or finally blocks

---

src/stages/main/patchers/InOpPatcher.js
test/in_test.js

Fixes #482
Now that the code uses `.includes`, it seems cleaner to use that always even
when the array operand is an array literal. Also, there were some precedence
issues with the logical operators case, so getting rid of it fixes those issues.

fix: remove logical operators case for `in` patching

---

src/stages/main/patchers/BinaryOpPatcher.js
test/binary_operator_test.js

Fixes #428
The code for handling for handling binary operators almost always deals with the
OPERATOR token from coffee-lex, but sometimes it deals with the EXISTENCE token
when `?` is used in a binary operator context.

fix: include the `?` operator as an allowed binary operator

---

package.json
test/function_call_test.js

This isn't strictly necessary due to semver rules, but it's nice in that it
forces the latest version and triggers a build. This change also adds a test for
the most recent fix.

fix: update decaffeinate-coffeescript to patch 5

---

src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

Fixes #511.
The new `patchAndGetCode` method is more robust than the previous approach,
especially in cases like soaks that add code to the start. Also, the code was
overwriting the target even if it didn't need to be extracted, which caused
problems in some cases, so only overwrite it if it's going to be replaced by
something different.

fix: improve handling of loop targets to get the right code

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

Fixes #520
It turns out that this-assignment works in a for-of loop in JS, so we can just
convert `for @a in b` to `for (this.a of b)`. The for-of conversion always
happens when there's a value assignee and no key assignee, so we can just always
patch the value assignee.

fix: patch the assignee when generating JS for-of loops

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/function_call_test.js

Fixes #417
Fixes #387
In some cases, the code path to insert the implicit close-paren in a function
call would create a new line with a properly-indented close-paren, but that
would confuse the CoffeeScript parser if the following token was a close-paren
at a greater indentation. Now, in that case, we put the close-paren next to the
following close-paren so the indentation can't get messed up.

fix: place implicit call close parens more carefully to avoid later parse errors

---

src/stages/normalize/index.js
src/stages/normalize/patchers/ArrayInitialiserPatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/stages/normalize/patchers/ObjectInitialiserPatcher.js
test/function_call_test.js

Fixes #447.
CoffeeScript is not particularly consistent about when to allow trailing commas
in multiline argument lists, array literals, and object literals. If the last
part of the argument or element is an implicit function call, then they are
allowed, but if the function call has parens, then the trailing comma is not
allowed. This means that the normalize stage can make code incorrect in some
cases, so we need to remove these unnecessary parens.

fix: remove unnecessary commas in the normalize stage

---

src/stages/main/patchers/TemplateLiteralPatcher.js
test/string_interpolation_test.js

Fixes https://github.com/decaffeinate/decaffeinate/issues/252
The previous strategy for finding the `#` character to replace was to look right
after the end of the previous quasi. However, if the string was a herestring
with removed indentation, then the quasi location wouldn't include that removed
indentation, so the `#` wouldn't be properly replaced. One possible fix is to
change the decaffeinate-parser locations, but ignoring removed indentation in
quasi locations doesn't seem unreasonable. Instead, the code now looks for an
INTERPOLATION_START token between the end of the quasi and the start of the
expression and uses that, which seems more reliable anyway.

fix: improve detection for # to $ replacement in string interpolations

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

Fixes #349
For the JS for-of case the expanded case, and the map case, we just need to make
the code a little more resilient to handle the case where the value assignee is
null, and insert code in the proper way.

fix: handle loops of the form `for [a..b]`

---

src/stages/main/patchers/FunctionPatcher.js
test/function_test.js

Fixes #456
We already have similar code for arrays and objects, so it was just a matter of
using the same approach for parameter lists.

fix: handle parameter lists with missing commas

---

src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/HerestringPatcher.js
src/stages/main/patchers/ObjectBodyMemberPatcher.js
test/object_test.js

Fixes #411
In most cases, object keys in CoffeeScript are just regular strings or
identifiers, so we can just patch them normally. But for template strings and
multiline herestrings, we need to put brackets around the string since those
types of object keys aren't allowed in JS. Also, for the specific case of a
template literal key with only a single expression, it's useful to just convert
that expression directly to the computed key form.

fix: properly insert brackets around object keys when necessary

---

src/stages/main/patchers/ThrowPatcher.js
test/throw_test.js

Fixes #503
Apparently CoffeeScript lets you put a newline between throw and the error,
while JavaScript doesn't. To fix, just remove that spacing if necessary. Note
that this can sometimes end up removing comments, so ideally we would find a
place to move them, but this seems like an unlikely place to put a comment in a
case that already seems relatively rare, so this is probably fine for now.

fix: allow throw statements containing a newline

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/super_test.js

Fixes #375
The code was placed at outerEnd, past the enclosing function call parens, when
it should have been placed at contentEnd.

fix: place `arguments...` in the right place for implicit super calls

---

src/stages/main/patchers/SwitchCasePatcher.js
test/switch_test.js

Fixes #449
The switch case code was assuming that because the consequent was in an implicit
return context, the code would return and no break was necessary. However,
that's not always true; in a conditional, there may be missing code paths,
meaning that no implicit return happens, so we need to also make sure that all
code paths exist.

fix: properly insert break statements in switches with conditionals

---

src/patchers/NodePatcher.js
test/new_op_test.js
test/soaked_test.js

Fixes #501
This is similar to #445, but that change tested exactly for the
`FunctionApplication` node (we can't reference patchers because `NodePatcher`
is independent of stage). But really, this happens in any case where we have an
argument list, so we need to broaden it to include new operations and soaked
function applications.

fix: properly set patching bounds for new and soaked function call operations

---

src/stages/main/patchers/ForOfPatcher.js
test/for_test.js

Fixes #538
In PR #518, I changed the `getTargetReference` call in for-of loops to be under
a conditional, which meant that in some cases (when the target was repeatable),
the target wouldn't be patched at all. To fix, we can just always patch the
target, but only sometimes overwrite the actual target code with the reference.

fix: always patch the target in for-of loops

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/function_call_test.js

Fixes #540
CoffeeScript expects that if an argument list is just one line, then the
close-paren is also on that line. I mostly already handled that case by checking
if the function call node was multiline, but really I needed to be more careful
and check the argument list specifically, since sometimes the function
expression itself can span multiple lines while the argument list is only one
one line.

fix: properly place the implicit close-paren for multiline calls

---

src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
test/compound_assignment_test.js

Fixes #512
Existence assignment ops assume that if we're patching as a statement, we can
remain a statement (and thus change to an `if` statement), but the `__guard__`
approach to soak operations assumes that an assignment can have parens wrapped
around it. To avoid this conflict, we can have the existence assignment code
look ahead to see if there's a soak operation, and just do an expression-style
patch in that case. Since this should be a relatively rare case, the main goal
here is to just make sure the result is correct.

fix: use expression patching for existence assign ops with soaks

---

src/stages/main/patchers/SlicePatcher.js
test/slice_test.js

Fixes #524
In an expression like `a[b..-1]`, it's incorrect to use 0 as the second slice
arg, since that refers to the start of the string, not the end. Instead, we want
to just omit the second arg. In the more general case where the right side is a
variable, we need to add `|| undefined` so that if the result is 0, we
effectively pass no arg to the function.

fix: properly account for slice ranges ending in 0

---

package.json
src/utils/resolveToPatchError.js
test/utils/resolveToPatchError_test.js

esnext now exposes a `source` field on exceptions with the relevant source code
when the failure happened, so use that so we have better context on the error,
particularly in the repl.

fix: improve error reporting in esnext failures

---

package.json
src/stages/main/index.js
src/stages/main/patchers/BoundGeneratorFunctionPatcher.js
src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/ManuallyBoundFunctionPatcher.js
src/stages/main/patchers/ObjectBodyMemberPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
src/utils/traverse.js
test/function_test.js

Fixes #516
Generally bound generator functions can be converted to regular `function`
expressions with `.bind(this)` at the end, but there are various edge cases like
when the function is in an object or class body.
Also fix some issues with fat arrow functions referencing `arguments` not always
having `this` bound.

feat: implement bound generator functions

---

src/index.js
src/patchers/NodePatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/utils/convertNewlines.js
src/utils/detectNewlineStr.js
src/utils/getStartOfLine.js
test/newline_test.js
test/utils/convertNewlines_test.js
test/utils/detectNewlineStr_test.js
test/utils/getIndent_test.js

Fixes #550
We convert the newline style to \n at the start, then convert it to its original
style at the end. That way, decaffeinate can detect and generate \n newlines
without having to worry about the different styles.
There are some libraries out there for detecting and converting newline styles,
but they're a bit more complicated than I need and don't behave exactly the way
I want, and both operations are pretty easy to implement.
This change also means that we can simplify some of the code that was handling
CR characters. Generally, any code now can assume that '\n' is the only type of
newline.
Note that I don't make any attempt at supporting CR newlines. Hopefully Mac OS 9
is far enough in the past that we don't need to have to think about it.

fix: properly handle code with Windows newlines or mixed newline style

---

src/stages/main/patchers/SwitchCasePatcher.js
test/switch_test.js

Fixes #562
The switch case patcher does a magic-string remove operation from the start of
the `when` token to the start of the condition. When the condition was negated,
it would sometimes have a `!` inserted at the start that would then be removed
by this remove operation, producing incorrect code. To fix, we can just track
the negation and delay it until just before the conditions are patched.
Generally, this moves code toward the best practice of making sure magic-string
operations happen in order, and a similar strategy may be useful if other
patchers cause issues.

fix: in switch cases, defer negation until just before patching

---

src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Fixes #566
We negated the condition when `unless` was used in a statement context, but not
when it was used in an expression context.

fix: respect the isUnless flag when patching a conditional as an expression

---

package.json

decaffeinate and decaffeinate-parser need to share the same coffee-lex instance
or else singleton comparisons will fail, so this commit forces both decaffeinate
and decaffeinate-parser to depend on coffee-lex 4.x so they can use the same
instance.

fix: update decaffeinate-parser dependency to keep coffee-lex in sync

---

src/patchers/NodePatcher.js
src/patchers/types.js
src/stages/normalize/patchers/ConditionalPatcher.js
src/stages/semicolons/index.js
src/utils/escape.js

magic-string 0.17.0 deprecated insertLeft and insertRight in favor of more
precise prepend/append names. See this issue for a discussion on that:
https://github.com/Rich-Harris/magic-string/issues/109
To silence that warning, this commit moves the code to the new API, which was
pretty easy because there are only a few call sites.
I also cleaned up that part of `NodePatcher`, which didn't make a lot of sense.
Now, instead of `NodePatcher.insert` calling `NodePatcher.insertRight` calling
`MagicString.insertLeft` and `NodePatcher.insertLeft` being unused, we just
have `NodePatcher.insert` calling `MagicString.appendLeft`. At least for now, I
think it's best to always use the same insert method so that inserts go in
order.
I also changed insertRight to appendRight in one case because it …

fix: silence magic-string warnings and update usage

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

fix: don't crash on empty catch blocks with an exception assignee

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForOfPatcher.js
src/stages/main/patchers/FunctionPatcher.js
src/stages/main/patchers/LoopPatcher.js
src/stages/main/patchers/ProgramPatcher.js
src/stages/main/patchers/SwitchCasePatcher.js
src/stages/main/patchers/SwitchPatcher.js
src/stages/main/patchers/WhilePatcher.js
test/conditional_test.js
test/switch_test.js

Fixes #589
Switch expressions and conditional expressions can both be patched as IIFEs, in
which case they get to decide how to handle sub-expressions in an implicit
return position. However, neither of these classes implemented the methods to
declare that they are an implicit return patcher, so the code was using the next
ancestor instead when searching for the implicit return patcher. That meant that
a switch or conditional IIFE within a loop IIFE would include `.push` lines in
the inner IIFE when it shouldn't.
Another issue was that loop patchers were declaring themselves as an implicit
return patcher even when they were patched as a normal expression and not an
IIFE. I'm not aware of any correctness issues this caused, but it seems good to
fix.
To fix, I changed conditional, switch, …

fix: rework the implicit return protocol and fix several bugs with its usage

---

README.md
package.json
src/cli.js
src/index.js
src/stages/TransformCoffeeScriptStage.js
src/stages/add-variable-declarations/index.js
src/stages/esnext/index.js
src/stages/semicolons/index.js
test/import_test.js
test/support/check.js

Fixes #407.
This adds a new command line arg, `--keep-commonjs`, which disables that esnext
transform. To accomplish this, I made it so the decaffeinate options are sent to
every stage instead of just the filename. This should also make it a bit easier
to implement other options in the future.

feat: add an option to disable the conversion from require to import

---

docs/conversion-guide.md
src/cli.js
src/index.js
src/stages/esnext/index.js
test/declaration_test.js

Fixes #408.
While I'm at it, I made the CLI exit with an error message if it sees an invalid
argument. We've dropped support for node 0.12, so it's safe to use `startsWith`,
but the conversion guide hadn't been updated, so I also updated that.

feat: add an option to prefer const rather than let

---

package.json

Unfortunately it looks like this only gives a warning when installing on node
0.12 or earlier, but that's probably better than no warning.

fix: add an "engines" line to require node 4 in package.json

---

src/stages/main/patchers/ConstructorPatcher.js
test/class_test.js

Fixes #596
Fixes #597
When patching constructors when there are bound methods, we need to insert code
after the super statement, if there is one. This is inherently a bit fragile,
since magic-string works best when all code is patched in order. Previously, we
were patching the method body, then inserting the bindings, but that could cause
the new statements to be inserted after the `}`. To fix this, I made the code
smarter about patching order: it patches the function either before or after the
inserted statements to avoid interfering with the start or end. This solution
feels a bit hacky, but at least for now seems nicer than trying to actually
force everything to patch in order.
Also, the code was assuming that the body was non-null, so I added a special
case with a null body where we …

fix: rework constructor patching code to better handle bound methods

---

src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
test/compound_assignment_test.js

Progress toward #125
The expression patcher already had logic to detect if we need to do a `typeof`
check by seeing if there was already a declared variable, but the statement
patcher wasn't doing that check. Pull the checkout into a separate method and
use it everywhere.

fix: use `== null` when possible for `?=` statements

---

src/stages/main/patchers/SwitchCasePatcher.js
test/switch_test.js

Fixes #607.
Previously, we would detect if the switch case body ends with a `break` token,
but that's actually not good enough; we should directly check that the last
statement is a break statement.

fix: properly detect break statements within switch cases

---

README.md
src/cli.js
src/index.js
src/stages/normalize/index.js
src/stages/normalize/patchers/DefaultParamPatcher.js
src/stages/normalize/patchers/DoOpPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/stages/normalize/patchers/IdentifierPatcher.js
src/stages/normalize/patchers/MemberAccessOpPatcher.js
test/class_test.js
test/default_param_test.js
test/function_call_test.js
test/function_test.js

Fixes #125
Now, instead of converting CS default params to JS default params, the default
behavior is to emit assignments behind a null/undefined check. This is more true
to CS semantics: in CS, defaults are used when the argument is null or
undefined, while in JS, they are only used when the argument is undefined.
There was already similar code for handling `this` assignment in parameters, so
I based default parameter code off of that. There were various special cases to
consider:
* In a function like `(@a=b) -> c`, we need to generate code for both the
default assignment and the `this` assignment, and the variable names need to
match up.
* In a function like `({a}={}) -> b`, we need to do the null check before the
destructure since the null check needs to be on a regular variable, so we …

feat: implement strictly correct default params and enable them by default

---

src/stages/main/patchers/InOpPatcher.js
test/soaked_test.js

Fixes #606
The `includes` case of `in` patching needs to switch the order of the two
operands, and it was doing this by keeping the right one in place and moving the
left one to the right. However, this could miss some code patched to the left of
the left expression because we use `insertLeft` in magic-string. We can fix this
by simply patching the other way: moving the right side to the left. We can use
`patchAndGetCode` to get the proper patched code, and because the `remove`
operation overlaps `this.right.outerStart`, we don't need to worry about extra
code being left over.
For the same reason, I think in general it's more robust to move the right side
to the left when switching the order of two expressions.

fix: properly handle soak expressions combined with `in` operators

---

test/binary_operator_test.js
test/decaffeinate_test.js
test/for_test.js
test/function_call_test.js
test/function_test.js
test/indentation_test.js
test/parameter_assignment_test.js
test/semicolon_test.js

This brings the number of skipped tests down from 42 to 22. Some of these just
worked without needing any modification, and others were working in spirit, but
needed to be tweaked to match the current output. I also moved some tests out of
decaffeinate_test.js to a more appropriate place, and removed some duplicate
tests.

test: un-skip some now-passing tests

---

package.json
src/stages/main/patchers/LoopPatcher.js
test/conditional_test.js
test/switch_test.js

decaffeinate's code for handling IIFE-style loop expressions would insert a
`var` declaration for a temporary variable to receive the value for the current
iteration. But a `var` declaration is actually wrong, because in some cases it
would end up with the previous loop iteration's value, so we should generate
`let` instead.

fix: update esnext and fix a scoping issue introduced by the bug fix

---

docs/contribution-guide.md
src/patchers/NodePatcher.js
src/patchers/PassthroughPatcher.js
src/patchers/types.js
src/stages/main/patchers/ChainedComparisonOpPatcher.js
src/stages/main/patchers/DynamicMemberAccessOpPatcher.js
src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
src/stages/main/patchers/ExistsOpPatcher.js
src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
src/stages/main/patchers/MemberAccessOpPatcher.js
src/stages/main/patchers/ObjectInitialiserMemberPatcher.js
src/stages/main/patchers/ThisPatcher.js
test/chained_comparison_test.js

Progress toward #592
Previously, `makeRepeatable` was a function that you would call around the time
of `patch` (sometimes before, sometimes after) that would sometimes do some
magic-string operations to extract the expression into a variable. However,
this had some problems:
* To be friendly with magic-string, all code should be patched in order, meaning
that some of the `makeRepeatable` code should run before patching the node and
some should run after, rather than them being separate operations.
* Because there was no obvious relation between patching and `makeRepeatable`,
the `isRepeatable` case couldn't assume that the code was already patched and
just returned the old CoffeeScript code, which only worked in simple cases
like identifiers. Even if the expression was already patched, …

refactor: rework makeRepeatable to be more integrated with patching

---

src/patchers/types.js
src/stages/main/patchers/CompoundAssignOpPatcher.js
src/stages/main/patchers/DynamicMemberAccessOpPatcher.js
src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
src/stages/main/patchers/MemberAccessOpPatcher.js
test/binary_operator_test.js
test/soaked_test.js

Fixes #592
Patching for soak operations is a bit fragile because the `__guard__(` and the
close-paren are inserted in code outside of the soak operation itself. This is
made more complicated with repeatable expressions, since both want to surround
the code in similar ways.
In member access expressions (including soaked member access), the code to make
the expression repeatable needed more complexity to make it so the repeated
result is still a valid assignee, but this complexity was only needed in two
assignment cases. To limit problems caused by this approach, and make the code a
little nicer in some cases, the behavior is now opt-in: when making an
expression repeatable, you can pass an `isForAssignment` flag to indicate that
the patching needs to be done in a way that the repeated code …

fix: only use assignment-style repeatable expressions when necessary

---

README.md
src/cli.js
src/index.js
src/stages/main/patchers/ForInPatcher.js
test/continue_test.js
test/for_test.js
test/semicolon_test.js
test/slice_test.js
test/switch_test.js

Fixes #523
decaffeinate now uses `Array.from` in both JS for-of loops and when using
`map`/`filter`, which handles the case where the loop target is an array-like
object (with `length` and numerical indices) instead of a real array (which is
iterable and has `map` and `filter`).
I made two separate prefs for these, since it looks like there are many more
array-like objects in the wild without `map` and `filter` (or where the
semantics are different, e.g. jQuery collections) than there are array-like
objects that are not iterable. But both seem to exist, so to stay on the safe
side, I'm wrapping in `Array.from` by default in both cases. It may make sense
to enable `--loose-for-of` by default in the future if it's deemed safe enough.

feat: change loops and loop expressions to be strictly correct by default

---

src/stages/main/patchers/ManuallyBoundFunctionPatcher.js
test/function_test.js

Fixes #579
The function patching code was in some cases inserting a `}` at `innerEnd` and
then inserting `.bind(this)` at `contentEnd`. Usually those are the same (and
this is a rare case anyway, so it didn't come up much), but in the example in #579,
`innerEnd` was after the newline and `contentEnd` was before, so `.bind(this)`
was being added to early. To fix, I changed the `.bind(this)` code to go at
`innerEnd`, which generally follows the rule that patching should go in order.

fix: avoid out-of-order patching in manually bound functions

---

README.md
src/cli.js
src/index.js
src/stages/main/patchers/InOpPatcher.js
test/function_call_test.js
test/in_test.js
test/soaked_test.js

Fixes #636
There was already code to optionally surround in parens, so we just needed a new
case to optionally surround in `Array.from(` and `)`. As with other `Array.from`
usages, I added a flag to disable this behavior if people are confident that
they're only working with arrays or otherwise objects that have `includes`.
Also go through some old tests and fix their names to better reflect what's
actually done.

feat: implement strictly-correct `in` patching by default

---

src/stages/main/patchers/ForInPatcher.js
src/utils/Scope.js
src/utils/countVariableUsages.js
src/utils/parse.js
test/for_test.js
test/utils/Scope_test.js
test/utils/countVariableUsages_test.js

Fixes #635
In some cases, we would change a variable to a parameter when converting an
expression-style loop, and this caused other usages to be invalid. In other
cases, there could be loop assignees like `@a` that aren't valid parameters (at
least not without additional work). To avoid these cases, we can add an
additional check when deciding patching style, where we only proceed if all
assignees are just identifiers and if those identifiers are only used within the
loop itself.

fix: don't use `map` when a loop assignee can't safely be a parameter

---

src/stages/main/patchers/ForOfPatcher.js
test/for_test.js

Fixes #644
For `null` and `undefined`, this causes the loop to not iterate, which is
consistent with CoffeeScript. For `false`, `0`, `''`, and `NaN`, the behavior
was already to not iterate, so the behavior is unchanged.

fix: add a null check when converting for-own to Object.keys

---

src/stages/main/patchers/AssignOpPatcher.js
test/expansion_test.js

Progress toward #107
We already had code to handle expansion nodes, so non-terminal rest is almost
the same, we just need to produce one more assignment that slices the middle
part of the array.
I also reworked some of the code to use `patchAndGetCode` when possible and to
patch code in order as much as we can.
The plan is to implement non-terminal rest and expansion for parameters by moving
the trailing parameters to an array destructure in the normalize step, so we'll
only need one code path that needs to think about the details of generating this
type of code.

feat: implement non-terminal rest in array destructures

---

src/stages/normalize/index.js
src/stages/normalize/patchers/ExpansionPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/stages/normalize/patchers/SpreadPatcher.js
test/expansion_test.js

Fixes #107
Progress toward #268
This change works off of #646 to implement expansion and non-terminal rest for
parameters. The code change ended up being pretty straightforward: at the
normalize step, we just take the comma-separated list of arguments and move them
to an array destructure on the first line. This ends up playing nicely with the
other code handling default params and this assignment.
I'm not calling #268 closed quite yet because decaffeinate doesn't yet handle
nested expansions or intermediate rests, which I've seen in at least one
real-world case.

feat: implement expansion and intermediate rest params

---

src/patchers/NodePatcher.js
test/compound_assignment_test.js

Fixes #649
magic-string doesn't allow slicing where either end is in a range that has been
removed, which occasionally can cause problems in `captureCodeForPatchOperation`
when we want to get the code added before the start index. Normally, we subtract
1 to find the snippet of code just before the start of the expression, but
really, subtracting any amount will work, so keep on subtracting one more until
magic-string doesn't throw an exception. This feels a bit fragile, and it's
possible that magic-string could expose a better API here to make the check more
robust, but at the very least, we'll throw an error if every index fails.

fix: handle errors when getting code while patching a node

---

src/stages/main/patchers/BlockPatcher.js
test/function_call_test.js

Fixes #648
Various code paths use `getBoundingPatcher` to determine the latest index that
we can safely patch code, which is especially important when a line ends with
close-parens and/or close-braces that close outer nodes. The
`insertStatementsAtIndex` method can be used to add a line to the end of a
block, but it wasn't doing this check, so in some cases it would incorrectly
insert the new line after a close paren that's supposed to be after the block.

fix: don't patch past the end of the expression in insertStatementsAtIndex

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.js
test/binary_operator_test.js

Fixes #611
Unlike JavaScript, CoffeeScript binds assignment operators tighter than most
binary operators (for reasons that I haven't quite been able to figure out by
reading the source code; the operators table has assignment at lower precedence,
but it's also right-associative, so maybe that affects things, or maybe there's
other code to decide precedence). We already were passing a `needsParens` flag
to children of binary operators, but assignment operators were ignoring that
flag, so no parens were added, so the JS precedence rules would be used. To
avoid this issue, we can simply respect that flag when patching all types of
assignment operators, which ends up fixing the issue without changing the output
of any existing tests.

fix: add parens when instructed when patching assignment operators

---

.flowconfig

This can happen, for example, when doing an `npm link` with a package that has these packages as development dependencies.

chore: ignore these packages wherever they appear

---

src/stages/main/patchers/EqualityPatcher.js
test/chained_comparison_test.js
test/comparison_test.js
test/function_test.js
test/logical_operator_test.js

Fixes #656
`EqualityPatcher` already extended `BinaryOpPatcher`, and `BinaryOpPatcher`
already exposes a way to customize operator patching, so we can just use that
and we'll also pull in the needsParens behavior (importantly, telling child
assignment expressions to add parens). This adds parens in a few cases where
they're unnecessary, which is arguably a little uglier, but eslint has an
auto-fixer for this with the no-extra-parens rule, so that probably handles
typical use cases if people care.

fix: change EqualityPatcher to respect the needsParens flag

---

src/stages/normalize/patchers/ForInPatcher.js
test/for_test.js

Fixes #661
When rearranging a node, we should patch the children first, then work with the
patched results. For for-in loops in particular, we were patching the step after
everything else, so patching the step could cause magic-string problems. An easy
fix is to just reorder it so we patch the step first.

fix: patch the step before rearranging loops in the normalize stage

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

Fixes #658
There were two problems:
* We were inserting the IIFE code at `outerStart` and `outerEnd`, but that means
that the parens would end up inside the IIFE, which wouldn't work. Instead,
insert at `contentStart` and `contentEnd`.
* There was a special case for if the expression was surrounded by parens, but
if so, it would skip wrapping the arrow function in parens. But arrow
functions need to always be in parens, so we'll always need them, and it's
simpler and correct to just get rid of that case. We could potentially
repurpose the existing expression parens to use in the IIFE, but that seems
like it's probably not worth it.

fix: properly patch try expressions surrounded by parens

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

Fixes #665
The code in TryPatcher was assuming that the try body always exists, but it
turns out that's not true, so we need to add null checks in various places.

fix: handle the case where a try body is null

---

src/patchers/NodePatcher.js
src/stages/main/patchers/IdentifierPatcher.js
test/conditional_test.js
test/try_test.js

Fixes #678
Previously, the default behavior was to insert at `outerStart`, which would
usually crash if the expression was surrounded by parens, since `outerStart` is
outside the editing bounds in that case. We can't rely on having parens anyway,
so any subclasses should (and already do) add extra parens if necessary.

fix: change the default negate function to insert at contentStart

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

Fixes #680
Looks like `then` can appear even if the catch block is null.

fix: properly remove the `then` token in try statements

---

src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForPatcher.js
src/stages/main/patchers/WhilePatcher.js
src/stages/normalize/patchers/ForInPatcher.js
src/stages/normalize/patchers/ForPatcher.js
src/stages/normalize/patchers/WhilePatcher.js
test/for_test.js
test/while_test.js

Fixes #663
We want to avoid an unparenthesized `then` token in a `while` condition, since
that will confuse the CoffeeScript parser. Ideally, maybe we'd tokenize the new
condition that results from the normalize step, or detect this case in some
other fancy way, but an easy approach that works is to just see if `then` is a
substring of the expression code, and defensively wrap in parens if so.
The same issue comes up for `for` as well, so take a similar approach there.
These tests also exposed some issues with `for` and `while` patching in general,
mainly that we weren't setting fields to be expressions when we should have, and
we were using too lenient of a range when finding the `then` token after a loop.

fix: wrap loop components in parens in the normalize stage if necessary

---

.eslintrc
package.json
src/utils/Scope.js
src/utils/isReservedWord.js
src/utils/resolveToPatchError.js
test/function_test.js

Fixes #666
Also add some additional error checking to avoid an infinite loop when trying
variable names, and make error formatting more robust to handle a NaN end index,
which apparently comes up sometimes. Also tweak the eslint config to allow
`new Set`.

fix: don't generate identifier names that are reserved words

---

src/stages/main/patchers/MemberAccessOpPatcher.js
src/stages/main/patchers/SoakedMemberAccessOpPatcher.js
test/soaked_test.js

Fixes #691
This gets parsed as two nested accesses, one for the `a?::` and one for the `b`
(with an implicit preceding `.`), so I also needed to change some of the normal
member access code to handle that. I think this will also make the
`ProtoMemberAccessOp` node type unnecessary.

feat: handle soaked prototype access

---

package.json
src/stages/main/index.js
src/stages/main/patchers/HeregexPatcher.js
src/stages/main/patchers/InterpolatedPatcher.js
src/stages/main/patchers/RegexPatcher.js
src/stages/main/patchers/StringPatcher.js
src/utils/escapeSpecialWhitespaceInRange.js
test/regular_expression_test.js
test/string_test.js

Fixes #672
For the most part we can just do some overwrite operations on regions of code
that we know are string contents, but we also need to be careful to avoid
inserting `\u2028` if there's already a backslash there, since otherwise the
resulting string will be `\\u2028`.

fix: handle \u2028 and \u2029 characters in strings and regexes

---

src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js
src/stages/main/patchers/SoakedFunctionApplicationPatcher.js
src/stages/main/patchers/SoakedMemberAccessOpPatcher.js
src/utils/findSoakContainer.js
test/soaked_test.js

Fixes #699
This ended up not being so bad: we can just get the from the start of the soak
container to the start of the soak operation and move it to within the guard
call.

feat: implement soaked prefix operations

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

Fixes #708
This ensures that we include any open-parens at the start of the expression.

fix: use patchAndGetCode when patching loop steps

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/SlicePatcher.js
test/slice_test.js
test/support/validate.js

Fixes #668
This is heavily based off of the slice patching code, with some modifications.
It's also a little strange in that the slice patcher patches only part of the
slice call and the assign op patcher patches the rest, but that seemed like the
cleanest way to do it with the way things are structured now.

feat: implement splice operations

---

.flowconfig

This makes it possible to `npm link` in the decaffeinate-coffeescript package
without flow errors.

chore: ignore jsonlint in .flowconfig

---

test/support/check.js
test/support/validate.js

I've been working on top of this diff for a while since it makes my dev workflow
easier, so I figured I'd send a PR since maybe it's a nice change in general.
Importing from `src/index` directly means that you can run `mocha` directly
without building each time (which is especially nice for tests within WebStorm),
and loading the source files directly means that debugging through source files
just works. The downside is that if rollup did end up introducing correctness
issues, the tests now wouldn't catch them. But decaffeinate-parser and
coffee-lex use this strategy as well, so it seems ok.
I kept the `"pretest": "npm run build",` line in package.json since I think it's
still useful to verify that build, lint, and flow all work, especially in CI.

chore: change test code to point at source rather than dist code

---

src/patchers/NodePatcher.js
test/array_test.js

Ensure that array elements are considered bounding patchers. This prevents, for example, appending trailing `}` for functions outside the array.
Closes #716

fix: do not insert code outside array elements

---

docs/contribution-guide.md

In #714, I realized that the guide doesn't discuss commit message format at all. This adds the same basic info I added to that pull request.

docs: add information about commit message format

---

src/utils/determineIndent.ts
tslint.json

This fixes a consistent crash caused by #735 where any non-trivial file would
fail due to `detectIndent` not being defined. From what I can tell, rollup can't
handle the `import detectIndent = require('detect-indent');` line and was just
ignoring it, so `detect-indent` was never pulled in and everything broke when it
tried to use that method.
A little ironic that this would have been caught by tests were it not for #712.
But probably it's still fine to leave the tests as testing the source code and
not the dist build.

fix: un-break CLI by changing detect-indent import to a form recognized by rollup

---

src/patchers/NodePatcher.js
test/object_test.js

Fixes #740
I think fixes a regression from #719.
The assertion that we edit with bounds should be a little more lenient than the
code that limits writing to the bounding patcher. We already had a case for that
for function parameters, so add one for array elements as well.
The resulting code in the test is a bit ugly, but at least it doesn't crash.

fix: make edit bounds checking within an array more lenient

---

README.md
src/cli.js
src/index.js
src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ClassBlockPatcher.js
src/stages/main/patchers/ConstructorPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/utils/babelConstructorWorkaroundLines.ts
src/utils/getInvalidConstructorErrorMessage.ts
src/utils/types.js
test/class_test.js
test/support/assertError.js

Fixes #591
Fixes #726
A major difference between CoffeeScript and JavaScript class constructors is
that JavaScript class constructors require you to call `super` and require it
to be called before the first use of `this` (when the class is a subclass).
This has caused two significant issues in decaffeinate:
* CS code that uses `this` before `super` or omits `super` will convert to code
that is rejected by babel. This happened for 11 files in my codebase.
* Subclasses that use bound methods will put the binding code after the `super`
call, while the CoffeeScript semantics are to put it before the `super` call.
This caused (at least) two correctness issues in my codebase, only one of
which was caught the tests. (Both of these were backbone subclasses where the
`initialize` method gets …

feat: more intelligently handle invalid constructors

---

src/stages/main/patchers/AssignOpPatcher.js
test/slice_test.js

Fixes #751
I mistakenly thought `Array.from` would do what I want, but it actually just
happens to work for single-character strings because `Array.from('a')` is
`['a']`. Instead, we should use `concat` like CoffeeScript does (which has its
own rules about when to keep something an array and when to treat the arg as a
single element). I also made the tests a little more interesting to expose this
case.

fix: correctly handle splice operations on an individual element

---

package.json
src/stages/main/patchers/ArrayInitialiserPatcher.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ModuloOpCompoundAssignOpPatcher.js
src/stages/main/patchers/SlicePatcher.js
src/utils/canPatchAssigneeToJavaScript.js
test/declaration_test.js
test/expansion_test.js
test/slice_test.js

Fixes #268
CoffeeScript assignment has some differences from JavaScript assignment in a few
ways:
* CoffeeScript allows the expansion operator (`...`).
* CoffeeScript allows intermediate rest assignments.
* CoffeeScript allows splice operations at any point in an assignment.
* CoffeeScript destructure defaults will fall back to the default if the value
is `null` or `undefined`, unlike JS, which only falls back if the value is
`undefined`.
* CoffeeScript array destructuring happens by accessing `arr[0]`, etc, while
JavaScript destructuring uses the iterable protocol.
Assignment patching now has two code paths: the "normal" patching code path, and
the "expanded" code path. We use the normal code path when possible, which
translates the assignee in a straightforward way, but if any part of …

feat: overhaul assignment patching to allow nested destructuring

---

src/stages/normalize/patchers/FunctionPatcher.js
test/class_test.js
test/expansion_test.js
test/parameter_assignment_test.js

Fixes #755
Now, instead of inserting all default param assignments followed by all `this`
assignments, we generate the new assignment lines in parameter order. This also
makes the normalize FunctionPatcher arguably a little cleaner because it pulls
out the code for individual parameter patching into its own function. Also,
since array destructuring works fully now, we can skip default and this assign
for parameters that will get extracted as rest params.

fix: evaluate parameter assignments in order

---

src/stages/normalize/patchers/ForPatcher.js
test/for_test.js

Fixes #757
This is implemented by creating a new variable and moving the assignee to the
start of the loop if necessary, so that we can reuse the existing assignment
expansion code in the main stage. This also required reworking the post-for code
a bit.

feat: handle complex loop assignees

---

src/stages/normalize/patchers/FunctionPatcher.js
src/stages/normalize/patchers/SpreadPatcher.js
test/class_test.js
test/expansion_test.js

Fixes #756
Currently, this is implemented by taking the first parameter that can't be
converted in a straightforward way and moving everything from there later to a
rest param in the normalize step. This lets us reuse code for complex
assignments in the main stage. This certainly has some room for improvement,
since in some cases it would be nice to do complex assignments without using
rest params, but code like this is probably rare enough that it's not worth
worrying about too much.

feat: handle complex function parameters

---

src/patchers/NodePatcher.js
src/stages/main/patchers/DynamicMemberAccessOpPatcher.js
src/stages/main/patchers/MemberAccessOpPatcher.js
src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js
src/stages/main/patchers/SoakedFunctionApplicationPatcher.js
src/stages/main/patchers/SoakedMemberAccessOpPatcher.js
test/soaked_test.js

Fixes #704
In some cases, a soak operation could place a close-paren at the end of the soak
container before the normal suffix for the soak container node. To avoid this, I
added a way to defer a code snippet to be inserted at the end of a node once it
is finished patching.
It's almost the case that you can just apply the suffix code at the end of the
`patch` method, except that the code for handling repeatable expressions needs
to sometimes include the suffix code in its repeat code. So code handling
repeatable expressions needs to be aware of the deferred suffix mechanism, but
hopefully that will stay fairly small-scoped.

fix: defer the soak close-paren until after the soak container is patched

---

src/stages/normalize/patchers/ConditionalPatcher.js
src/stages/normalize/patchers/ForInPatcher.js
src/stages/normalize/patchers/ForPatcher.js
src/stages/normalize/patchers/WhilePatcher.js
src/utils/postfixExpressionRequiresParens.ts
test/conditional_test.js
test/for_test.js
test/while_test.js

Fixes #762
We already had code to wrap intermediate expressions in parens if they have a
`then` inside them, and it turns out that a newline can also cause problems, so
extract the condition inso a simple shared function and use it for all
reordering that we do in the normalize step.

fix: in the normalize step, wrap some multiline expressions in parens

---

src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #690
We do this in the normalize stage rather than the main stage, since we'll need
to account for it in case we need to generate the `initClass` method.

fix: remove the `then` token for single-line classes

---

src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Fixes #763
* In one case, we just weren't placing the `}`.
* BlockPatcher would sometimes have `setImplicitlyReturns` called when empty
(due to only having a block comment that gets removed from the AST). Just
ignore it in this case.

fix: don't crash on some edge cases involving empty conditionals

---

.gitignore
src/patchers/NodePatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/member_access_test.js

I didn't bother with a bug. I just added a test (previously failing).
[eval](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=Q%20-%3E%20P%20-%3E%0D%0A%20%20foo%0D%0A.then%20(bar)%20-%3E%0D%0A%20%20bar)

fix: insert close-paran without breaking member access

---

src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Fixes #774
We used to remove from the end of the consequent to the start of the else in the
expression case, but that can destroy comments, so be more conservative now.
Also, if we have a block with 0 statements in an expression context, we should
use `undefined` instead of having no contents at all.

fix: better handle comment-only blocks in conditionals

---

src/stages/main/patchers/SuperPatcher.js
test/class_test.js

Fixes #771
In CoffeeScript, super can be called from a direct prototype assignment and from
within a nested call in a method, but neither of these cases is allowed in
JavaScript. To handle these, we now sometimes do some extra work to directly
call the right method on the prototype.

fix: allow super calls in more cases allowed by CoffeeScript

---

src/stages/main/patchers/YieldFromPatcher.js
src/stages/main/patchers/YieldPatcher.js
test/function_test.js

Fixes #776
For many expression cases, JavaScript requires parens around yield expressions,
so we need to add them unless we know it's safe not to. yield in a statement
context, yield in a return, and yield on the RHS of an assignment all do not
require parens, so we skip the parens in those cases.

fix: wrap yield expressions in parens when necessary

---

package.json
src/stages/main/index.js
src/stages/main/patchers/YieldReturnPatcher.js
src/utils/traverse.js
test/function_test.js

Fixes #688
It behaves almost the same as `return`, except we need to remove the `yield`
token and mark the function as yielding.

feat: implement `yield return`

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/member_access_test.js

Fixes #777
This feels like a bit of a hack, unfortunately, but it's the only thing I could
think of the works in all cases. Rather than placing the close-paren just before
the following dot, we move the dot to be just after where the close-paren would
go, which generally might join the two lines, and might end up destroying an
inline comment, but handles all known cases without crashing.

fix: avoid placing close-parens with too much indentation

---

package.json
src/patchers/SharedProgramPatcher.js
src/stages/main/patchers/ProgramPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
src/stages/normalize/patchers/ProgramPatcher.js
test/class_test.js

Fixes #625
The general strategy here is to define an `__initClass__` helper in the
normalize stage which calls the `initClass` static method. This is uglier than
the previous approach of adding an `initClass` statement after the class
definition, so we dynamically decide which of the two to use, preferring the
statement approach. Since the normalize stage does not properly communicate
whether patching is done as an expression, we just look at the AST and only
allow the `initClass` statement if we're a child of a block and not in an
implicit return position.
Also, the existing code for handling helpers was all for the main stage, so I
factored it into a `SharedProgramPatcher` that also works in the normalize
stage.
This almost fixes #544, but there's a remaining issue in that example …

feat: handle class expressions for complex classes

---

README.md

Fixes #804
(At least, I hope so!)
Hosting directly from GitHub while getting caching right is a bit tricky, but it
looks like GitHub pages has nicer response headers so that the content type is
correct and the cache expiration is relatively short.

docs: update README table badges to gh-pages SVGs

---

package.json
src/stages/normalize/index.js
src/stages/normalize/patchers/BareSuperFunctionApplicationPatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/utils/traverse.js

There's now a `BareSuperFunctionApplication` node type that simplifies the
checks we needed to do. As before, it gets turned into its expanded form in the
normalize stage.
This also pulls in a fix to chained comparisons and unary operators.

fix: update decaffeinate-parser to latest

---

src/patchers/NodePatcher.js
src/stages/main/patchers/FunctionApplicationPatcher.js
src/stages/main/patchers/SpreadPatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/utils/formatDecaffeinateParserAst.js

The AST now never has any virtual nodes, so we can get rid of some special cases
in a few places.

refactor: remove `virtual` checks on AST nodes

---

src/stages/main/patchers/BlockPatcher.js
test/class_test.js
test/function_test.js
test/indentation_test.js
test/return_test.js

Fixes #816
The previous logic was to remove trailing empty returns by deleting from the
start of the previous newline to the end of the return, but if there was code
after the `return` on the same line and the previous line had a comment, it
could cause that code to be pulled into the comment.
To fix, I rewrote the logic so it only removes the line if the `return` is on a
line by itself. If not, it does the safe thing of just removing the `return`.
This makes some generated code cleaner, but ends up with an unnecessary blank
line in the `initClass` method for complex class expressions. I couldn't find a
clean solution to avoid this, so it's a style regression in this commit,
favoring correctness in other cases. I think probably the right solution there
is to rethink that code transform so …

fix: don't put code in comments when removing trailing empty returns

---

src/stages/normalize/index.js
src/stages/normalize/patchers/AssignOpPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
test/binary_operator_test.js

Fixes #790
Apparently CoffeeScript allows `then` after any type of assignment, and it
doesn't do anything in particular, so we can just remove it in the normalize
stage.
Also, the assign op patcher in the normalize stage had a `key` field when it
should have been `assignee`, so fix that.

fix: remove unnecessary `then` tokens after assign operators

---

src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #828
Inner classes had a special case that they usually need to be turned into an
assignment, but for this-assigned inner classes, it's correct to leave them
alone.

fix: don't generate an assignment for this-assigned inner classes

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ExistsOpCompoundAssignOpPatcher.js
src/stages/main/patchers/ExistsOpPatcher.js
src/stages/main/patchers/IdentifierPatcher.js
src/stages/main/patchers/UnaryExistsOpPatcher.js

This makes it easier to determine when we need to do a `typeof` check, and
will be useful for some upcoming changes to soak operations that will need
to do a similar check.

refactor: add a `mayBeUnboundReference` to `NodePatcher`

---

src/patchers/NodePatcher.js
src/stages/main/patchers/CompoundAssignOpPatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/SoakedMemberAccessOpPatcher.js
src/utils/nodeContainsSoakOperation.js
src/utils/ternaryNeedsParens.js
test/compound_assignment_test.js
test/for_test.js
test/soaked_test.js

Progress toward #801
Progress toward #336
Now, with a simple soak expression like `a?.b`, it will be expanded into a
ternary rather than using the `__guard__` function. This allows us to handle the
case where the variable is unbound (in which case the code should return
`undefined` rather than throwing an exception). More specifically, we use the
conditional form of soak operations
As described in #336, I separate the expression and statement cases and prefer
to wrap in an `if` if possible.
This only handles the case for normal soaked member access; a later commit will
expand it to soaked dynamic member access and soaked function application.
Also fix a subtle bug in repeatable expression patching where a paren could be
misplaced.

feat: avoid the guard helper in some soaked member accesses

---

src/stages/main/patchers/SoakedDynamicMemberAccessOpPatcher.js
src/stages/main/patchers/SoakedFunctionApplicationPatcher.js
test/function_call_test.js
test/soaked_test.js

Fixes #801
Progress toward #336
We now use a conditional for soaked dynamic member access and soaked function
calls as long as the expression is repeatable and does not contain any soak
operations.
This is pretty much the same strategy as for soaked member accesses. For
function calls, the code naturally becomes method call syntax when necessary, so
we don't need a special case for methods like with the `__guardMethod__` stuff.
There's some duplicated code, but a lot of helper methods have been shared and
there are enough differences that it seems reasonable to have the duplication
for now and try to consolidate later if it becomes a bigger issue.

feat: avoid the guard helper in some additional soak cases

---

package.json
src/stages/main/patchers/DoOpPatcher.js
src/stages/normalize/patchers/DefaultParamPatcher.js
test/do_test.js

Fixes #784
Fixes #637
We already had a special case for handling `do` expressions with a function
expression, but we need to exercise the same logic in the case when there is an
assignment with a function RHS.

fix: properly handle assignments within `do` expressions

---

src/utils/ternaryNeedsParens.js
test/soaked_test.js

Fixes #836
We need to wrap a soak ternary in parens when it is negated.
This fixes the last test failure in coffeelint!

fix: properly handle `unless` and `until` with a soak condition

---

package.json
src/stages/main/patchers/ProgramPatcher.js
test/comment_test.js
test/conditional_test.js

Fixes #838
A decaffeinate-parser change made some AST node bounds different (generally for
the better), which broke a test. This also exposed a regression where
decaffeinate could `insertLeft` at the end of a block comment, and then later
when the comment was transformed, it would overwrite that new code. Instead, we
now transform comments first.
Also add a skipped test for a case I discovered where we destroy a comment.

fix: update tests, stop comment patching from overwriting other code

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/BinaryOpPatcher.js
test/soaked_test.js

Fixes #840
Rather than immediately surrounding an expression in parens, we should set a
flag on the expression so it gets an open-paren at the start of patching and a
close-paren at the end. There still could potentially be some conflicts between
deferred patching and patching at the end of an expression, but it seems to not
come up at least for this issue.

fix: change negated patching to patch in order

---

src/stages/normalize/index.js
src/stages/normalize/patchers/ClassPatcher.js
src/stages/normalize/patchers/ConstructorPatcher.js
test/class_test.js

Fixes #830
We handle external constructors in the normalize step, since it generates
another line in `initClass` and that way we don't need to worry about handling
bound methods and `super` issues at the same time.
Note that this does not yet handle external constructors in experession-style
classes, but should should start working once #835 is addressed.

feat: allow external constructors in classes

---

src/stages/main/patchers/SuperPatcher.js
test/super_test.js

Fixes #843
For most super calls, we can convert them to JS super without needing a
reference to the enclosing class. However, in more advanced cases, we'll need a
reference to effectivelly call super ourselves. CoffeeScript generates code
where even anonymous classes can be referenced, so we may need to do that at
some point in the future. For now, though, we should just convert to JS super
rather than failing if we can't find a name for the enclosing class and it's a
simple case that can become JS super.

fix: don't crash on a simple super call within an anonymous class

---

package.json
src/stages/main/patchers/BoundFunctionPatcher.js
src/stages/main/patchers/ManuallyBoundFunctionPatcher.js
test/new_op_test.js

Fixes #846
We need to stop the function from becoming an arrow function if it is used with
`new`.

fix: allow `new` to be used on bound and unbound functions

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/FunctionPatcher.js
src/stages/main/patchers/SuperPatcher.js
src/utils/extractPrototypeAssignPatchers.js
test/super_test.js

Fixes #844
In the general case, we need to handle both normal prototype member access and
dynamic member access, and both the class expression and the member access
expression need to be made repeatable. Fortunately, the relatively new
repeatable protocol makes this relatively easy to accomplish.

fix: allow super within prototype-assigned methods in more cases

---

src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/ObjectBodyMemberPatcher.js
test/class_test.js
test/object_test.js

Fixes #847
This simplifies the computed key logic to only happen in one place, and ensures
that at least for the normal key case, we actually end up calling patch on the
key. I think some additional work will be necessary to do the equivalent for
static methods, but this should handle the common case.
This also changes the behavior so method name strings aren't surrounded by
brackets, but it turns out that wasn't necessary.

fix: allow computed keys for class methods

---

src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #851
There was already some code to special-case the indent level for single-line
classes, so we just needed to reuse it when generating the constructor.

fix: properly format external constructors in single-line classes

---

src/stages/main/patchers/ClassPatcher.js
test/class_test.js

Fixes #853
The code to put a name for the class was actually wrong, since it introduces a
name when it shouldn't. And in this case, it also introduced the use of a
keyword as an identifier, which caused a crash.

fix: don't specify a class name for namespaced classes

---

src/stages/main/patchers/ClassPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
src/utils/Scope.js
test/class_test.js

Fixes #855
We now track class declarations in our scope, and only use the normal class
syntax if the class being patched is also the declaration site (the first
assignment seen by the scope).
This also lets us remove a special case in the `initClass` patching in the
normalize step. We don't need to explicitly create an assignment anymore,
because one is created automatically due to a variable with the same name being
declared above the class declaration.

fix: allow duplicate class declarations

---

src/stages/main/patchers/ClassPatcher.js
src/utils/isReservedWord.js.flow
src/utils/isReservedWord.ts
test/class_test.js

Fixes #861
This is mostly a revert of #854, although I also added some additional logic to
check if the generated name is a reserved JS word (copying CoffeeScript's set of
names) and add an underscore if so. I also added some tests to ensure that the
behavior matches CoffeeScript for these cases.

fix: properly set the class name for complex class declarations

---

src/patchers/NodePatcher.js
src/patchers/types.js
src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ClassBlockPatcher.js
src/stages/main/patchers/ConstructorPatcher.js
src/stages/main/patchers/ObjectBodyMemberPatcher.js
src/utils/getBindingCodeForMethod.js
test/class_test.js

Fixes #858
The basic idea is that we make sure all bound method keys are repeatable and
that method bindings are patched after the bound method keys are, then use that
information if necessary to generate a method binding line using square bracket
notation.
There were some nuances here:
* We now need to change the patching order so constructors are patched last, so
that we have the patched values for method names to bind. This means that we
need to explicitly do so in BlockPatcher, and in the case where we introduce
the constructor, we want to introduce it at the top of the class but after the
class contents are patched. Since normally patching needs to be done in order,
I added a way to use the `prependLeft` method from magic-string for special
cases where we know that patching needs to …

fix: allow computed keys for the names of bound methods

---

src/stages/main/patchers/ClassPatcher.js
test/class_test.js

Fixes #867
Unlike in JavaScript, CoffeeScript named classes assign to their outer scope, so
we need an explicit assignment unless we know the class will be a JS class
declaration statement.

fix: always generate an assignment for expression-style classes

---

src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/SuperPatcher.js
test/super_test.js

Fixes #869
When we have a method containing `super`, we mark the name as repeatable, then
in the super call, we get that repeat code if necessary.
Note that this doesn't yet address static methods. Those will need to be handled
in the fix for #860.

fix: allow super within methods with non-identifier names

---

src/stages/main/patchers/UnaryOpPatcher.js
test/unary_operator_test.js

Fixes #872
The previous logic for unary operators was to propagate the `needsParens`
patching flag to the child, but that actually isn't valid. Even if the unary
operator is in a context where it doesn't need additional parens (e.g. a
conditional), its operand might be a binary operator that needs parens, so just
pass true for `needsParens`.

fix: properly specify parens under unary operators

---

src/patchers/NodePatcher.js
src/stages/normalize/patchers/ArrayInitialiserPatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/stages/normalize/patchers/ObjectInitialiserPatcher.js
src/utils/normalizeListItem.js
test/array_test.js
test/function_call_test.js
test/function_test.js
test/object_test.js

Fixes #856
In the normalize step, we just replace the semicolon with a comma, except at the
end of a parameter list when we need to just remove it.

fix: allow semicolon delimiters for lists

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/LoopPatcher.js
src/stages/main/patchers/SwitchPatcher.js
src/stages/main/patchers/TryPatcher.js
test/conditional_test.js
test/for_test.js
test/switch_test.js
test/try_test.js

Fixes #857
The loop case already handled this, so getting it working in all cases just
meant moving that code up to `NodePatcher` and using it in all of the IIFE
cases.

fix: properly use generators for IIFEs when necessary

---

src/patchers/NodePatcher.js
src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/ExistsOpPatcher.js
src/stages/main/patchers/ObjectInitialiserPatcher.js
test/object_test.js

Fixes #689
There's a lot of logic to find a nice-looking place for the open-brace, but
generally it might be in a safe place that's before our bounds. But that means
that other patchers, like the exists op patcher, might have already written
there. To avoid this, we now call `adjustBoundsToInclude` to effectively
"reserve" that area. This required a little bit of extra care so that we only
actually adjust the bounds when we're being patched as an expression, and
ExistsOpPatcher needs to patch its child as a statement when necessary.

fix: avoid bounds error when patching an implicit object literal

---

src/stages/main/patchers/ForOfPatcher.js
test/for_test.js

Fixes #884
In some cases, some code could end up left over on the left side after patching
the target, due to using magic-string's `appendLeft`. To avoid this, we can
always do an overwrite operation for the target and its surrounding code when we
know that we're extracting the target into a variable.

fix: properly patch code around for-of loop targets

---

src/index.js
src/utils/removeUnicodeBOMIfNecessary.ts
test/decaffeinate_test.js

Fixes #891
Unicode byte order mark characters normally aren't a problem for us, except that
CoffeeScript has a special case to remove them at the start, so it gives all
source indexes as if the BOM was removed. To avoid running into issues there, we
can just do the same. As with newline formats, this is just handled at the
decaffeinate layer and coffee-lex and decaffeinate-parser can assume the simpler
format (although they could also be made more robust later if it's useful).

fix: remove the Unicode BOM if necessary at the start of the code

---

src/patchers/NodePatcher.js
test/indentation_test.js

Fixes #893
Rather than crashing when we run into an unexpected indentation issues, we
should just silently ignore them for now. In the test case, the generated code
ended up being fine anyway.

fix: don't crash on files with mixed tabs and spaces

---

src/stages/normalize/patchers/FunctionApplicationPatcher.js
test/function_test.js

Fixes #744
In some cases, the computed `innerEnd` (which usually defines the editing
bounds) can be strictly before the following close-paren, so trying to patch at
the start of the following close-paren will give an error. In other cases, we
need to patch after `innerEnd` and the editing bounds are extended. To handle
both cases, we allow patching up to the end of the editing bounds, but not
further.

fix: don't patch out of bounds when placing close-parens

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ObjectInitialiserPatcher.js
test/object_test.js

Fixes #898
One issue was that the patching bounds were not properly accounting for object
parents, so add that case. That fixed the correctness issues, but resulted in
ugly code. To avoid inserting a newline unnecessarily, we only add a newline
before the close-curly if we are multiline or if our enclosing object
initializer is multiline.

fix: properly handle nested implicit object initializers

---

src/stages/normalize/patchers/ConditionalPatcher.js
src/stages/normalize/patchers/ForPatcher.js
src/stages/normalize/patchers/WhilePatcher.js
src/utils/postfixNodeNeedsOuterParens.js
test/conditional_test.js
test/for_test.js
test/while_test.js

Fixes #896
Whenever an if/while/for is in a non-final position in a comma-separated list
and is followed by a comma token, rearranging it will confuse the parser because
the comma will be seen as part of the body. In these cases (which we can detect
by seeing if the node has a comma after it), we can wrap the node in parens to
avoid the ambiguity.

fix: surround postfix if/while/for in parens when necessary

---

src/stages/normalize/patchers/ArrayInitialiserPatcher.js
src/stages/normalize/patchers/FunctionApplicationPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/stages/normalize/patchers/ObjectInitialiserPatcher.js
src/utils/normalizeListItem.js
test/array_test.js
test/function_call_test.js

Fixes #886
Fixes #887
This feels a little like a hack, but seems to work in all cases that I know of,
and hopefully is at least enough flexibility to get through the long tail of
crazy parser cases for the normalize stage. As part of patching any list
(function args, function parameters, array values, object values), we now
analyze the tokens between all adjacent list items and fix them up if necessary:
* If there are two commas (which can happen when one is immediately after an
object initializer), we get rid of the second one.
* If the RHS is an object initializer, then in some cases it could be
reinterpreted as a function call, so add an explicit comma. However, in other
cases (when the LHS is something like a conditional with a block body), skip
the comma. As far as I can tell, these …

fix: add more cases to fix delimiters between list items

---

README.md
src/cli.js
src/index.js
src/stages/main/patchers/ChainedComparisonOpPatcher.js
src/stages/main/patchers/EqualityPatcher.js
src/utils/isCompareOpNegationUnsafe.ts
test/chained_comparison_test.js
test/comparison_test.js
test/switch_test.js
test/while_test.js

Fixes #902
For both normal binary operators and chained comparison operators, we need to be
careful about rewriting `!(a < b)` as `a >= b`, since the rewrite isn't correct
for cases like `NaN`. Now, we just do the simpler negation by default and only
do the nicer-looking one with an opt-in flag.

fix: don't unsafely negate operators like `>` by default

---

src/utils/canPatchAssigneeToJavaScript.js
test/expansion_test.js

Fixes #880
The complex assignment code path generates an assignment for each destructured
value, so we can get the right behavior by using that on an empty destructure.
This means we can skip the `Array.from` and avoid crashing if it would be
invalid.

fix: generate no assignments for an array destructure

---

src/stages/main/patchers/SlicePatcher.js
test/slice_test.js

Fixes #882
We need to put a `+` unary op at the front to avoid string concatenation when
adding `1`.

fix: ensure that inclusive slice bounds are numbers

---

src/stages/main/patchers/AssignOpPatcher.js
test/expansion_test.js
test/for_test.js
test/slice_test.js

Fixes #881
There were a few fixes here:
* For normal expression-style assignments where the RHS is wrapped in
`Array.from`, we need to return the original unwrapped RHS, so make it
repeatable and return it via a comma expression.
* For this new case, make sure we wrap expression in parens to avoid precedence
issues.
* For the normal complex assignment case, always wrap is in parens if it's an
expression, not just when it starts with a `{`, since we want to avoid
precedence issues with the comma operator. In some cases, like the return
case, this is unnecessary, but that seems not worth worrying about, and IMO
it's better to wrap an assignment expression in parens anyway.

fix: make sure complex assignments have the right return value

---

src/utils/canPatchAssigneeToJavaScript.js
test/expansion_test.js

Fixes #908
Just fall back to the more precise algorithm in this case (generating one
assignment per destructured value, like CS does).

fix: generate non-crashing code on empty object destructure on undefined

---

src/stages/normalize/index.js
src/stages/normalize/patchers/TryPatcher.js
src/utils/PatchError.js
src/utils/Scope.js
test/try_test.js

Fixes #585
Catch assignees have different scoping rules in CoffeeScript and JavaScript, so
the simple way to solve that is to generate an assignment at the start of the
catch block so the variable is function-scoped. This is always correct, but
usually ugly, so we only do it in the rare cases where it's necessary:
* when the variable is actally used outside of the catch block.
* when the variable is a complex assignment instead of just an identifier, e.g.
a destructure with an expansion node. Even though JS does support some forms
of exception destructuring, for simplicity, we always extract non-identifiers.
From a code standpoint, this is similar to how normalize ForPatcher moves the
assignee to the start of the body when necessary.
Also fix scope assignment traversal to account for …

fix: extract catch assignees to assignments when necessary

---

src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/DoOpPatcher.js
test/conditional_test.js
test/declaration_test.js
test/do_test.js
test/slice_test.js

Fixes #912
As with various other cases, it's safer to add parens by default and omit them
in a list of cases where they're known to not be necessary. This ended up
simplifying some other assignment code that needed to detect some cases where
parens were necessary.
It turns out that `do` expressions had some similar issues involving parens, so
I also made them add parens by default.

fix: add parens around assignments in more cases

---

src/utils/canPatchAssigneeToJavaScript.js
test/expansion_test.js

fix: traverse into rest nodes when checking if an assignee can become JS

---

src/stages/main/patchers/AssignOpPatcher.js
test/soaked_test.js

Fixes #916
This feels a little hacky at the moment since there isn't a clear answer to when
we should insert code at the end of an expression normally vs using
`appendDeferredSuffix`. But generally I think it's reasonable to say that
`appendDeferredSuffix` should be used in cases like close-parens where we want
it to wrap the whole resulting expression (after any other deferred code).

fix: correctly place close-paren in an expression assignment containing a soak

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ArrayInitialiserPatcher.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ForPatcher.js
src/stages/main/patchers/FunctionPatcher.js
src/stages/main/patchers/ObjectInitialiserPatcher.js
src/stages/main/patchers/SpreadPatcher.js
src/stages/main/patchers/TryPatcher.js
test/spread_test.js

Fixes #918
JS requires argument spreads to be iterable and not just array-like (even though
babel allows them to be array-like), so like with a bunch of other cases we wrap
in `Array.from` to be 100% correct. It turns out single-argument function call
spreads get compiled differently (the value doesn't get passed to `slice`), so
we need to add an additional check there to accept null or undefined.
I also needed to set up a system to distinguish assignee expressions from
non-assignee expressions. Technically, decaffeinate-parser could do this, and
attempts to in one simple case, but it seems easier and more useful to implement
it on the decaffeinate side.
Note that this is still technically not quite right for single-argument function
call spreads, since in that case non-null non-undefined …

fix: implement strictly correct argument and array spreads

---

src/patchers/NodePatcher.js
src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #835
Rather than the previous `__initClass__` wrapper function that called the
`initClass` static method, we now use an IIFE whenever the class is "complex
enough". Complex enough means one of the following:
* The class is used in an expression context (or, we can't prove it's in a
statement context).
* The class has variables that need to be extracted (since we need to create
a scope for them).
When we do this IIFE wrapping, we also need to indent the whole class. Due to
magic-string subtleties, we need to indent the whole class body before patching
any children, so a lot of the logic needed to be refactored so we can determine
at the start whether that indentation will be necessary.
Rather than handling anonymous classes (and other similarly-tricky classes) by
passing them into a …

fix: overhaul complex expression-style classes

---

src/stages/main/patchers/InterpolatedPatcher.js
src/utils/escape.js
test/regular_expression_test.js

Fixes #923
The lexer already breaks up the heregex into tokens of actual string content, so
we should just do escape operations over those tokens, ignoring padding
characters. Also, the escape function was looking past the end of the string,
but if `\` is at the end of a content token then we don't want to match
characters past it, so limit the skip matching to the end of the token being
considered.

fix: handle heregexes with a double-backslash followed by a space

---

src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/SwitchPatcher.js
src/stages/main/patchers/TryPatcher.js
test/conditional_test.js
test/switch_test.js
test/try_test.js

Fixes #925
In all three of these cases, we would mark our children but not ourselves as
implicitly returning. This makes sense in most cases because implicitly
returning means we get turned into an expression, which often isn't ideal. The
problem is that if we end up as an expression for any other reason (e.g. the
node is surrounded by parens), the implicit return will be skipped and the code
will be incorrect. So now we always record ourselves as implicitly returning
(which happens before we know whether we are going to be an expression), and
skip the implicit return if we end up as a statement, since we know that in that
case it's safe.

fix: properly implicitly return for expression-style `if`, `switch`, and `try`

---

README.md
src/cli.js
src/utils/getInvalidConstructorErrorMessage.ts

There was a blog post about decaffeinate relatively recently, so add it to the
README as further proof that it actually works.
The Babel constructor workaround also happens to work on TypeScript code (and
babel 5), so seems worth calling out.

docs: add blog post link, update docs for babel workaround

---

src/stages/normalize/patchers/ConditionalPatcher.js
test/conditional_test.js

Fixes #933
Similar to #620, the robust way to switch the order of two code snippets is to
move the right to the left, to avoid issues where an `appendLeft` at the start
of an expression doesn't get picked up by a `slice`. Rewriting postfix
conditional code to use this strategy avoids a case where we reordered a postfix
conditional around a postfix loop in a way that resulted in incorrect code.

fix: properly handle reordering when patching postfix conditionals

---

src/stages/main/patchers/ConditionalPatcher.js
test/conditional_test.js

Fixes #934
Conditional negation was using the default behavior of just adding a `!` to the
front. When a negated conditional gets patched to a ternary, we need to wrap it
in parens to avoid precedence problems.

fix: properly handle negation of conditionals

---

src/stages/normalize/patchers/BlockPatcher.js
test/class_test.js

Fixes #935
In some cases, a line gets indented in the normalize stage, and then we try to
fix indentation by removing some indentation. This can cause too much whitespace
to be removed overall. Instead, we now check every character before removing it
to make sure it's the original single whitespace character, and skip it if not.
There are some more clever strategies that we could use if there's ever a case
where we need to remove more whitespace than we can with this algorithm, but we
crash if we can't find enough whitespace, so that should be easy to detect and
seems unlikely anyway.

fix: be more careful when removing whitespace to fix indentation

---

src/utils/postfixNodeNeedsOuterParens.js
test/conditional_test.js
test/for_test.js
test/while_test.js

Fixes #748
`a if b; c` is a conditional followed by a statement, but `if b then a; c` has
`a; c` as the conditional body. To avoid this, we can always wrap these types of
statements in parens if there's a semicolon after them.

fix: wrap postfix statements in parens when followed by a semicolon

---

src/stages/normalize/patchers/BlockPatcher.js
test/class_test.js

Fixes #544
It looks like CoffeeScript allows commas between class items and they behave the
same as semicolons, so just change them to semicolons. We do this between all
adjacent statements in all blocks since it's easy, but I think it will only do
anything within classes.

fix: normalize commas to semicolons between class statements

---

src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/FunctionPatcher.js
test/binary_operator_test.js
test/conditional_test.js
test/function_call_test.js
test/instanceof_test.js
test/return_test.js
test/semicolon_test.js
test/sequence_test.js
test/switch_test.js
test/throw_test.js
test/try_test.js

Fixes #945
In CoffeeScript, regular statements, like `return`, `break`, etc, are allowed to
be surrounded by parens, and CoffeeScript emits code with the parens removed, so
we need to follow that behavior. In general, when a statement is surrounded by
parens, we might as well remove the parens and treat it as statement (if it was
going to be a statement already), since that usually looks better anyway.
This also means we can wrap statements in parens when generating them in the
normalize stage without making the code uglier, which will be nice for a later
fix.

fix: prefer to remove parens when a statement is surrounded by parens

---

test/conditional_test.js
test/for_test.js
test/while_test.js

Two mostly-independent changes landed in parallel, but one affected the test
output of another, causing a failure.

fix: fix test failures

---

src/stages/normalize/patchers/FunctionPatcher.js
test/default_param_test.js

Fixes #729
This avoids some precedence issues that can come up if the default value has an
arrow function in it.

fix: wrap default param assignments in parens

---

src/stages/main/patchers/SeqOpPatcher.js
test/for_test.js
test/sequence_test.js

Fixes #941
Previously, SeqOp was a binary operator, so it forced both of its operands to be
expressions. But CoffeeScript is actually a little looser and allows either one
to be a statement if the SeqOp itself is a statement. This is why you can
sometimes use `break`, `continue`, or `return` inside a SeqOp. To fix, I change
it to no longer be a binary operator and only force its children to be
expressions when it is an expression.

fix: allow sequence operations to be patched as statements

---

src/stages/main/index.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/SlicePatcher.js
src/stages/main/patchers/SoakedSlicePatcher.js
src/utils/traverse.js
test/soaked_test.js

Fixes #871
For the most part these can derive from the existing slice/splice code. Also
refactor splice code a little so the SlicePatcher can control both the beginning
and end of the code snippet.

feat: implement soaked slice and splice operations

---

src/utils/formatCoffeeScriptAst.js
test/utils/formatCoffeeScriptAst_test.js

Fixes #738
I just took the simple approach of allowing up to 2 levels of array nesting,
rather than supporting an arbitrary number of levels. I think that should be
fine.

fix: improve repl output for CoffeeScript switch statements

---

src/index.js
src/stages/TransformCoffeeScriptStage.js
src/stages/add-variable-declarations/index.js
src/stages/esnext/index.js
src/stages/semicolons/index.js

Closes #119
It didn't work anyway, since esnext doesn't support source maps, and made it
sort of a pain to add new stages or work with the code outside of stages.
I still kept around the response format of an object with a `code` property
rather than making it just a string, since I have vague plans for decaffeinate
outputting a list of warnings or cleanup suggestions or things like that, and
having a flexible output format would make that easier.

refactor: get rid of source map code

---

src/stages/main/patchers/BoundFunctionPatcher.js
src/stages/main/patchers/FunctionPatcher.js
test/class_test.js
test/function_call_test.js
test/function_test.js
test/indentation_test.js
test/return_test.js

Fixes #787
We already had some custom logic for non-arrow functions to place the
close-brace right before a close-paren on the next line, but that wasn't
happening for arrow functions. To fix, I factored it out into shared code used
in both places, and tweaked some of the logic in case the close-paren is at the
end of the line.

fix: improve close-brace placement for arrow functions

---

src/stages/main/patchers/FunctionPatcher.js
test/function_test.js

Fixes #958
Normally there's a CALL_END right after the function, but if the function itself
is wrapped in parens, we actually just want to take the RPAREN instead so we
don't get mismatched parens.

fix: consider enclosing parens when placing a function close-brace

---

src/stages/main/patchers/SwitchCasePatcher.js
test/switch_test.js

Fixes #958
The switch case bounds were wrong here, which I think is another CoffeeScript
parser bug, but I'm not 100% sure. Regardless, it's easy and safe to just look
for `then` as the next token, so I'll do that as a fallback.

fix: always remove `then` tokens from switch cases

---

src/stages/main/patchers/ProgramPatcher.js
test/binary_operator_test.js

Fixes #964
Also add a warning, since this seems a bit fragile. But there are certainly some
cases where we no longer care about the continuation token because other code
got rid of it.

fix: skip continuation tokens where the range has already been overwritten

---

src/patchers/NodePatcher.js
src/stages/main/patchers/SwitchCasePatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/utils/normalizeListItem.js
src/utils/postfixNodeNeedsOuterParens.js
test/object_test.js

Fixes #970
Previously, any semicolons would be changed to commas in list items, but
sometimes, the semicolon is actually the end of a statement. In that case,
changing it to a comma would cause problems, so we just remove it instead, since
it's not necessary.

fix: handle list items ending in semicolon-terminated statements

---

src/patchers/NodePatcher.js
src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/LoopPatcher.js
src/stages/main/patchers/SwitchPatcher.js
test/function_test.js
test/object_test.js
test/switch_test.js

Fixes #978
The new spec for implicit returning is that the parens are always kept and must
be handled by the implicit return code if necessary. For `return`, we want to
keep the parens to avoid ASI issues (and since we know it will always be an
expression). For `break` in `switch`, we need to remove the parens if they
exist, so add a special case for that. In loops, the issue doesn't seem to come
up; parens aren't allowed around `break` or `continue` in loops.

fix: don't remove parens for implicitly-returned expressions

---

src/stages/main/patchers/TryPatcher.js
test/try_test.js

Fixes #986
In some cases, we would try using `map` instead of an IIFE for a try within a
loop, which only works if the try can actually be used in an expression context.
When a try has a statement like `continue`, we need to disallow it from becoming
an expression.

fix: properly set canPatchAsExpression for TryPatcher

---

src/patchers/NodePatcher.js
src/stages/main/patchers/SwitchPatcher.js
test/switch_test.js

Fixes #987
Since we can generally assume the CoffeeScript we get is valid, it's generally
the case that any `break` and `continue` statements that are implicitly returned
should just be kept as-is, so we now apply that more broadly in `NodePatcher`.
In particular, a `break` within a non-IIFE switch that's implicitly returned was
causing a crash.

fix: skip implicitly-returned break and continue in more cases

---

src/stages/main/patchers/ClassPatcher.js
test/class_test.js

Fixes #988
Various code snippets inserted at the end of the class are already inserted at
`innerEnd`, so if we write to `contentEnd`, we might end up putting the
close-paren too early.

fix: add class expression close-parens at innerEnd

---

src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/ForInPatcher.js
test/try_test.js

Fixes #993
`throw` is an example of a node type that can patch as an expression, but
prefers not to. Our existing BlockPatcher code was using that to say that the
block could not be patched as an expression when actually it could, so
decaffeinate was crashing on valid code. Fixing this had some cascading effects,
and generally some more code needed to be more precise about prefering an
expression vs requiring an expression.

Change canPatchAsExpression to be more precise

---

src/patchers/NodePatcher.js
src/utils/ternaryNeedsParens.js
test/soaked_test.js

Fixes #995
When a node is negated and then changed to a ternary as part of a soak
operation, we weren't always adding parens when we needed to. In particular,
when the expression was already surrounded in parens, the soak code would view
extra parens as unnecessary even though a `!` had been inserted within those
parens. Now, we track when we negate in that way and always add parens in that
case when changing a soak container to a ternary.

fix: properly handle negated parenthesized soak operations

---

src/stages/main/patchers/ReturnPatcher.js
test/conditional_test.js

Fixes #1002
In some cases, CoffeeScript allows you to `return` something that cannot be
converted to an expression according to CoffeeScript's rules, such as a
conditional containing control flow statements. We now allow this by removing
the `return` at patch time and marking the expression as implicitly returning.

fix: convert explicit returns to implicit returns when necessary

---

README.md
src/cli.js
src/index.js
src/stages/literate/index.js
test/literate_test.js

Fixes #714
I maybe should have taken a simpler approach, but this was a fun exercise.
There's now an optional stage at the start that turns literate CoffeeScript into
regular CoffeeScript with some tweaks to make the result look nice. I don't use
magic-string, and instead just produce an array of lines that gets joined into
the final source code, which seems fine because source maps are unlikely to
happen and going line-by-line is a little easier for this case.

feat: add support for Literate CoffeeScript

---

src/stages/literate/index.js
test/literate_test.js

Since CoffeeScript block comments have a meaningful indentation level, it's
actually unsafe to insert them anywhere in the file, since indentation
differences can cause the normalize stage to break. Instead, we now take the
boring approach of always using `//` comments. Theoretically, we could be
smarter about this and convert them to multiline comments on the JS side where
the indentation doesn't matter, but that seems like it's probably not worth it.

fix: avoid block comments when processing literate coffeescript

---

src/cli.js

Fixes #1007
This fixes a regression caused by #1005 where the computed filename was only
changed if the original filename ended in .coffee, .litcoffee or .coffee.md.
Really, we want to keep the old behavior and always change whatever file
extension we find (or just add .js if there's no extension). But to properly
handle .coffee.md we should just special-case that.
I tested this manually, but plan to add automated tests for the CLI pretty soon.

fix: always replace the extension with .js

---

test/mocha.opts

This should avoid timeouts in the CLI tests.

test: increase the test timeout to 10 seconds

---

.travis.yml

This reverts commit 5b9df237e659fb08e14d8042ac0a77931939fb21.
The original `GH_TOKEN` value was compromised in [some sort of vulnerability](https://blog.travis-ci.com/2016-11-23-security-vulnerability-environment-variables/). I created a new one, so we can use it instead of the one you so graciously contributed @alangpierce 😉

fix: Revert "fix: tweak travis config to make releases work again"

---

package.json

Attempting to do this manually didn't work, apparently, as my `GH_TOKEN` was rejected. This commit isn't actually needed to fix anything, but I figured we might as well use the newer semantic release setup.

chore: re-run `semantic-release-cli setup` to re-configure for releases.

---

src/stages/normalize/patchers/DefaultParamPatcher.js
src/stages/normalize/patchers/FunctionPatcher.js
src/utils/getAssigneeBindings.js
test/function_call_test.js
test/function_test.js

Fixes #1010
We resolve parameter assignments in the normalize stage, so the way to ensure
that they're scoped to the function is to add `var`. To avoid excessive
independent variable declarations, we only do this when there's actually a
variale in the outer scope.

fix: avoid parameter assignments assigning to outer variables

---

src/stages/main/patchers/HeregexPatcher.js
src/stages/main/patchers/InterpolatedPatcher.js
src/utils/escapeSpecialWhitespaceInRange.js
src/utils/escapeZeroCharsInRange.js
test/regular_expression_test.js
test/string_test.js

Fixes #1028
In other cases, we don't remove intermediate whitespace, so we don't need to
worry, but for heregexes we might e.g. have `\0 1`, which would convert to
`\01`, which is an octal literal. Instead, we always convert `\0` to `\x00`.
This is a little dumber than CoffeeScript's approach, since we always do the
conversion in heregexes and CoffeeScript only does it if the next character is
0-7, but this case seems rare enough that we don't need to be too clever about
it.

fix: properly handle \0 chars in heregexes

---

src/stages/main/patchers/ChainedComparisonOpPatcher.js
test/chained_comparison_test.js
test/soaked_test.js
test/support/validate.js

Fixes #1034
I also changed the test code to do strict primitive checks, which it wasn't
doing before.

fix: surround ChainedComparisonOpPatcher in parens when necessary

---

README.md
docs/correctness-issues.md

Some tests in the CoffeeScript test suite are scrict/obscure enough that it's
probably not worth it to change decaffeinate to make the tests pass. It seems
fine to disable those tests as long as the correctness issues are documented, so
this commit gets started on that documentation.

docs: add a partial list of known issues

---

README.md

I think I need an explicit closing tag and then the links will work.

docs: don't try to use self-closing spans in the README

---

README.md

Apparently GitHub-flavored markdown filters out all spans.

docs: use `a` instead of `span` for IDs

---

test/chained_comparison_test.js
test/class_test.js
test/conditional_test.js
test/expansion_test.js
test/for_test.js
test/function_test.js
test/regular_expression_test.js
test/slice_test.js
test/soaked_test.js
test/spread_test.js
test/string_integration_test.js
test/string_test.js
test/support/assertDeepEqual.js
test/support/validate.js
test/unary_operator_test.js

Previously it was doing a JSON conversion to avoid the issue of prototype
differences between V8 contexts, but now it uses a custom deep equality function
instead.
Also, it now compares the result when run directly in V8, to guard against
differences between babel and V8. This required changing the spec to call a
function on the result rather than assigning the result to a variable.

test: rework the validate function to be more flexible

---

src/stages/normalize/patchers/FunctionPatcher.js
test/expansion_test.js

Progress toward #1043
The general behavior was correct, but limiting the rest params to the ones
starting at the expansion was wrong, since variables can reference earlier
values in the param list.

fix: correctly handle expansion params with too few args specified

---

src/stages/main/patchers/ClassPatcher.js
src/stages/main/patchers/FunctionApplicationPatcher.js
src/stages/main/patchers/ManuallyBoundFunctionPatcher.js
src/stages/main/patchers/NewOpPatcher.js
test/class_test.js
test/new_op_test.js

Fixes #1039
We now only skip the parens in the common cases of identifiers and member access
expressions.

fix: be more defensive when wrapping the `new` operand in parens

---

src/stages/main/patchers/AssignOpPatcher.js
test/expansion_test.js

Fixes #1043
We can get the correct behavior by effectively computing a new value to use as
the length, which is adjusted so that leftmost parameters after the rest param
are the first ones to get values if there are not enough values specified.

fix: properly handle intermediate rest destructure with too few values

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ArrayInitialiserPatcher.js
src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/BoolPatcher.js
src/stages/main/patchers/InOpPatcher.js
test/function_call_test.js
test/in_test.js
test/support/validate.js

Fixes #1038
This makes some cases uglier, unfortunately, but from a scan through my codebase
it seems relatively rare to have impure operands to the `in` operator.
I also added an `isPure` method that is very similar to `isRepeatable`, but
doesn't interfere with some cases where it's better for an expression to not be
repeatable even if it's technically pure.

fix: preserve order for `in` operations when necessary

---

src/patchers/NodePatcher.js
src/patchers/types.js
src/stages/main/patchers/InOpPatcher.js
test/in_test.js

Fixes #1052
Since the full expressions are in order for this case, it's best to just patch
in-place rather than getting the code, since otherwise some inserted
magic-string fragments can be left over and cause issues. Since the patching
strategy is different enough, I just made it a completely separate function.

fix: add a custom code path for the extracted variable `in` case

---

src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #1056
The existing `initClass` code path already properly handled this case, since the
arrow function binds the proper `this`, but we were treating it as a regular
method and effectively ignoring the fact that it was bound. To fix, we can just
add a special case to move it to `initClass`.

fix: properly handle bound static methods

---

src/stages/normalize/patchers/BlockPatcher.js

One change from https://github.com/decaffeinate/decaffeinate-parser/pull/222 is
that inline class blocks are now properly marked as inline. This caused
decaffeinate to go through a different code path that didn't change comma to
semicolon as necessary. Fixed by normalizing in that case as well.

fix: normalize separators within inline class blocks

---

package.json
src/stages/normalize/patchers/AssignOpPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Fixes #1057
Now that the parser correctly identifies the values as prototype assignments, we
can transform them when patching the body normally. We only do this for
properties that we know won't become methods.

fix: handle class fields within nested blocks

---

package.json
src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForPatcher.js
src/utils/Scope.js
test/for_test.js

Fixes #1044
We need to do this when the loop body might assign to the loop variable. We can
detect this by determining if there are any assignments to the variable directly
in the loop body or if there are any instances of the variabble assigned from a
closure anywhere in the function scope.

fix: extract loop variables to their own name when necessary

---

src/patchers/NodePatcher.js
src/stages/main/patchers/ConditionalPatcher.js
src/stages/main/patchers/ForPatcher.js
src/stages/main/patchers/LoopPatcher.js
src/stages/main/patchers/SwitchCasePatcher.js
src/stages/main/patchers/SwitchPatcher.js
src/stages/main/patchers/WhilePatcher.js
test/for_test.js
test/function_call_test.js
test/literate_test.js
test/switch_test.js
test/while_test.js

Fixes #1073
Previously, the general assumption was that all code paths (except ones
explicitly doing `continue` or `break`) in a loop would produce an array
element, but empty blocks and other similar cases should skip those.
This commit does a few things to fix that case:
* Get rid of the `item` case when generating loop expressions. Instead, loop
expressions *always* call `.push` in each condition (except empty blocks).
* For unspecified `else` and `default` cases, we now need to explicitly generate
an "empty case" if necessary. For the `return` style of implicit returns, the
implicit return patcher returns null to instruct that no code needs to be
added (since it will fall through and return `undefined`). I think this
behavior will also be useful in #1004, although I haven't …

fix: overhaul implicit return code to handle switch within loop expressions

---

src/stages/main/patchers/SwitchPatcher.js
test/for_test.js

The previous implementation had a chance of finding an unrelated `else` token,
so we need to change the search bounds to be more specific.

fix: properly detect the `else` token in switch statements

---

src/stages/main/patchers/AssignOpPatcher.js
test/class_test.js

fix: always repeat the method name for dynamic prototype assignments

---

src/stages/main/patchers/AssignOpPatcher.js
test/class_test.js

fix: repeat `this` expressions for dynamically-added methods using super in initClass

---

src/stages/main/patchers/ConditionalPatcher.js
test/for_test.js

We were patching in the wrong place in some cases. `innerEnd` is more reliable
here.

fix: properly handle incomplete conditionals ending in comments

---

src/patchers/NodePatcher.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/ObjectBodyMemberPatcher.js
test/class_test.js
test/super_test.js

Fixes #1082
In both computed method names and when computing the class to use in a dynamic
method assignment, we now save it to a variable so that at `super` time we know
it hasn't changed.
This makes some existing code uglier, and it could probably be improved by
adding some additional checks to see if the variables are ever reassigned or
modified, but all of these cases are obscure enough that this is probably fine
for now.

fix: make super code more defensive about computed names

---

src/stages/main/patchers/ForInPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

Fixes #1083
In order to have the proper index value both on the first iteration and after
the loop is finished, we need to put the index saving code in both the loop init
and the loop update code.
This also ends up implementing index saving for all types of loops, I think;
previously, range loops had the same bug.
The scope-related details are the same, but the other details have been
reworked; rather than there being an "index binding" and a "user-specified index
binding", we now have an "internal index binding" and an "index binding". The
loop details work with the internal binding, and save to the normal index
binding if they're different.

fix: rework loop index saving to happen within the init and update

---

src/stages/main/patchers/ForInPatcher.js
src/utils/Scope.js
test/for_test.js

Fixes #1084
The scope code is now smarter and distinguishes between variables being
declared, variables being modified, and variables being modified from an inner
closure. This allows us to account for cases like `++` and `+=` that modify a
variable without creating a binding.

fix: change loop index code to account for modifications

---

src/stages/main/patchers/ReturnPatcher.js
test/conditional_test.js
test/return_test.js
test/switch_test.js

Fixes #1004
As far as I can tell, unparenthesized conditionals and switches are the only two
cases where the behavior is different from simply treating the returned node as
an expression, so I special-cased those and reused the same logic as from an
earlier fix.

fix: handle incomplete returned conditionals and switches

---

src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/SuperPatcher.js
src/stages/normalize/patchers/ClassPatcher.js
test/class_test.js

Progress toward #860
Previously, static methods with computed names were put in `initClass`, even
though JS has a syntax for static methods with computed names. Now, we consider
them to be static methods just like any other and also get the details figured
out for handling `super` calls (which can be compiled into plain old `super`).
It's still possible to have `super` calls in `initClass` that accidentally
reference `initClass`, but this fixes the most common case of that.

fix: improve the output of dynamically named static methods

---

src/patchers/NodePatcher.js
src/stages/main/patchers/AssignOpPatcher.js
src/stages/main/patchers/ClassAssignOpPatcher.js
src/stages/main/patchers/FunctionPatcher.js
src/stages/main/patchers/SuperPatcher.js
src/stages/normalize/index.js
src/stages/normalize/patchers/AssignOpPatcher.js
src/stages/normalize/patchers/BareSuperFunctionApplicationPatcher.js
src/stages/normalize/patchers/DynamicMemberAccessOpPatcher.js
src/stages/normalize/patchers/MemberAccessOpPatcher.js
src/stages/normalize/patchers/SuperPatcher.js
src/stages/normalize/patchers/ThisPatcher.js
src/utils/containsSuperCall.js
test/class_test.js

Fixes #860
This `initClass` transform can reposition static methods so that they no longer
have the proper `super` semantics according to CoffeeScript's algorithm.
Instead, the `super` matches the `initClass` method itself. Since the code after
the normalize stage is incorrect, there's no way to fix this properly in the
main stage; instead, this commit moves some of the `super` logic to the
normalize stage, while most of it is still in the main stage.
This ended up being kind of a pain, but seems to be working. Some details:
* One role of the normalize stage is to add explicit arguments to all bare super
calls. Since I'm now doing some super transformations in the normalize stage,
I need to handle those two cases specifically.
* We need to extract out the `this` reference, but an …

fix: properly handle super calls within static methods in initClass

---

src/stages/TransformCoffeeScriptStage.js
src/stages/main/patchers/BlockPatcher.js
src/stages/main/patchers/ForPatcher.js
test/for_test.js

Fixes #750
The solution here is similar in spirit to #639, but has some differences.
Rather than allowing the loop to become an IIFE and letting
add-variable-declarations put in the declaration for us, we now explicitly add
declarations for any index/value bindings that we know will be in IIFEs, as long
as there is at least one usage of the variable outside of the loop. This
required a lot of coordination between BlockPatcher and all of its descendant
ForPatchers during initialize so that patching can be done in the proper order.

fix: properly add variable declarations for IIFE loop assignees

---

src/stages/main/patchers/ThrowPatcher.js
test/throw_test.js

fix: force `throw` targets to be expressions

---

package.json
src/stages/main/patchers/BlockPatcher.js
test/conditional_test.js
test/for_test.js
test/function_call_test.js

Fixes #1108
Now that all lone semicolons are treated in the AST as empty blocks, they turn
into `undefined` as expected when treated as an expression, but the semicolon is
still there. To fix this, we can just detect if the block ends in a semicolon
(even for non-empty blocks) and remove it.

fix: remove semicolons when turning blocks into expressions

---

eslint-rules/no-const-except-at-top.js
src/index.js
src/patchers/NodePatcher.js
src/patchers/types.js
src/stages/TransformCoffeeScriptStage.js
src/stages/add-variable-declarations/index.js
src/stages/esnext/index.js
src/stages/literate/index.js
src/stages/main/patchers/ClassBlockPatcher.js
src/stages/main/patchers/ConstructorPatcher.js
src/stages/semicolons/index.js
src/suggestions.js
test/chained_comparison_test.js
test/class_test.js
test/comparison_test.js
test/declaration_test.js
test/default_param_test.js
test/for_test.js
test/function_test.js
test/import_test.js
test/in_test.js
test/literate_test.js
test/suggestions_test.js
test/support/check.js
test/switch_test.js

Progress toward #1107
At the moment, we never print suggestions, but we do return them from the
convert function. Each suggestion has a shorthand code and a summary string, but
doesn't include any context like where in the code the transformation happened.
Suggestions are sorted by code, although in the future it may be better to
independently sort them by priority.

refactor: add an initial suggestions system that isn't hooked up

---

src/stages/main/patchers/BinaryOpPatcher.js
src/stages/main/patchers/ExtendsOpPatcher.js
src/stages/main/patchers/RangePatcher.js
test/binary_operator_test.js

Fixes #1113
Most binary operations have a plain operator token in them or already handled a
custom token type as a special case, but these two cases weren't handled.

fix: don't crash when using a binary operator with range or extends

---

docs/suggestions.md

Progress toward #1107
This gets most of the details that are good to know when cleaning up JavaScript
after decaffeinate, but I'm sure there are still some missing details.
Coming soon:
* Make the suggestions system provide suggestion codes for all relevant
suggestions in a file, which should help people know which parts of the doc
are most relevant to read.
* Link to this doc from other places.

docs: add an initial suggestions.md doc explaining each suggestion in detail

---

docs/suggestions.md

Progress toward #1107
Since suggestions are the main unit of organization in the doc, it's useful for
those headings to be underlined and to be able to easily jump to any section.

docs: use larger headers for the suggestions docs, add a TOC

---

src/index.js
src/suggestions.js
test/suggestions_test.js
test/support/check.js

Progress toward #1107
Rather than printing suggestions out to the console, I think it actually makes
more sense to include them in the code. This should make them really hard to
miss and be especially useful for the use case of doing a large conversion and
then going through each file as a follow-up task. I added a `disableSuggestions`
flag to disable this behavior if people want.
For now, the `disableSuggestions` is always set to true from the CLI, meaning
the feature can't be accessed normally now; it's just exposed to tests. I'll
change it to false by default soon along with all of the other breaking changes.

feat: insert suggestion comments in generated code

---

README.md
docs/correctness-issues.md
docs/suggestions.md
src/cli.js
src/index.js
src/stages/esnext/index.js
src/stages/main/patchers/ClassBlockPatcher.js
src/stages/main/patchers/ConstructorPatcher.js
src/utils/babelConstructorWorkaroundLines.ts
src/utils/getInvalidConstructorErrorMessage.ts
test/class_test.js
test/cli_test.js
test/declaration_test.js
test/import_test.js
test/suggestions_test.js
test/support/check.js
test/support/validate.js

Fixes #1107
Implement several defaults changes as described in #1107. This involved updating
the options structure, the CLI code, the docs, and the tests. This also includes
various other little cleanups to the docs and generated code to better match the
new system.
Also rename `disableSuggestions` to `disableSuggestionComment`, since maybe in
the future there will be a different way of displaying suggestions.
BREAKING CHANGE:
JavaScript files produced by decaffeinate now have a comment at the top of the
file with suggestions on cleanup steps. The new `--disable-suggestion-comment`
flag disables this behavior.
decaffeinate now prefers `const` for variables when possible. The
`--prefer-const` option is now a no-op, and a new `--prefer-let` option opts
into the old behavior.
decaffeinate no …

feat: enable suggestions system, update default options

---

src/stages/main/patchers/ForInPatcher.js
test/for_test.js

fix: don't generate useless `map` calls for array comprehensions

---

package.json
src/cli.js
src/patchers/NodePatcher.js
src/stages/main/patchers/InterpolatedPatcher.js
src/utils/PatchError.ts
src/utils/blank.ts
src/utils/canPatchAssigneeToJavaScript.ts
src/utils/containsSuperCall.ts
src/utils/printTable.ts
src/utils/resolveToPatchError.ts
src/utils/types.ts
test/utils/PatchError_test.ts
test/utils/resolveToPatchError_test.ts
yarn.lock

Also upgrade a bunch of dependencies to pull in proper types.
repeating didn't have types, but `String.prototype.repeat` is available in
node 4, so seems fine just get rid of repeating.

refactor: convert more utils files to typescript

---

test/string_integration_test.ts

These still run fairly fast on my machine, but seem to be super-slow on CI
recently, so just increase the timeout so the builds pass. Hopefully just a
travis issue that will fix itself.

test: increase string integration test timeout

---

test/decaffeinate_test.ts
test/support/check.ts

This didn't end up being the reason runToStage was broken in the repl, but a
test seems nice regardless.

test: add test for runToStage

---

package.json
src/patchers/NodePatcher.ts
src/stages/main/patchers/AssignOpPatcher.ts
src/stages/main/patchers/ClassAssignOpPatcher.ts
src/stages/main/patchers/ObjectBodyMemberPatcher.ts
src/stages/main/patchers/ObjectInitialiserMemberPatcher.ts
src/stages/main/patchers/ObjectInitialiserPatcher.ts
src/stages/normalize/patchers/MemberAccessOpPatcher.ts
src/stages/normalize/patchers/ObjectInitialiserMemberPatcher.ts
src/utils/blockStartsWithObjectInitialiser.ts
src/utils/canPatchAssigneeToJavaScript.ts
src/utils/formatDecaffeinateParserAst.ts
src/utils/getAssigneeBindings.ts
src/utils/leftHandIdentifiers.ts
src/utils/normalizeListItem.ts
yarn.lock

This fixes various little API changes.
I was hoping to get rid of `traverse` and `childPropertyNames`, but I think I
actually will need the names themselves instead of just the children, which will
require a decaffeinate-parser change.
Also fix a benign bug in `leftHandIdentifiers` on destructuring assignments with
defaults.

fix: update to the latest decaffeinate-parser

---

src/stages/main/patchers/ForInPatcher.ts
test/for_test.ts

Fixes #1170
The filter and map approach runs all filter calls first and then all map calls,
so if the filter has any side-effects, we can't use filter and map, so just fall
back to the normal expression loop case.

fix: don't convert loops to filter and map when the filter has a side-effect

---

src/patchers/NodePatcher.ts
test/function_test.ts

Fixes #1172
Ultimately, the issue was we had a block like `(a)` where `isSurroundedByParens`
was returning true. This meant that the bounding patcher was itself, even
though the block itself wasn't really surrounded by parens, it just started and
ended with parens. To fix, we can say the node isn't surrounded by parens in
this case, which means we're allowed to insert contents before the start of the
block.

fix: allow expanding the bounds of parenthesized function bodies

---

src/stages/main/patchers/JavaScriptPatcher.ts
test/javascript_test.ts

Fixes #1176
It looks like CoffeeScript handles embedded JS comments by removing all parens
around inline JS, even if it causes unintuitive behavior, so we copy that
behavior.

fix: remove parens surrounding inline JS expressions

---

src/patchers/NodePatcher.ts
test/object_test.ts

Fixes #1178
In some cases, we would insert a close-curly-brace for an object literal ending
in a semicolon, and the curly brace would go after the semicolon, which it
should go before.

fix: don't skip over semantic tokens when inserting new lines

---

src/stages/main/patchers/DoOpPatcher.ts
test/do_test.ts

Fixes #1189
We often can skip surrounding parens when we're already surrounded by parens,
but the parens around the do expression can't actually be skipped in that case,
since then the arguments might be applied with the wrong precedence.

fix: don't skip parens around do expressions surrounded by parens

---

src/stages/normalize/patchers/BlockPatcher.ts
test/object_test.ts

Fixes #1191
Previously, we only changed commas to semicolons between statements, but we
actually want to do it after the last statement in a block as well, which avoids
some problems involving trailing commas at the end of a file.

fix: convert comma statement terminators to semicolons in more places

---

src/stages/main/patchers/DoOpPatcher.ts
test/class_test.ts
test/do_test.ts
test/support/check.ts

Fixes #1193
We were sometimes competing with other code that inserted at innerEnd, so
contentEnd wouldn't work.

fix: add do expression close parens at innerEnd instead of contentEnd

---

src/stages/normalize/patchers/BlockPatcher.ts
test/function_test.ts
test/object_test.ts

Fixes #1195
The fix for #1191 relied on a change that had us editing beyond the block
bounds, which was causing lots of other problems. For now, I'll just limit the
comma-to-semicolon conversion to instances within the block, which I think
should fix the regressions but re-breaks #1191. The more fundamental issue in #1191
is bad parser location data (the comma isn't being included in any node bounds),
so probably the better fix will be in decaffeinate-parser or
decaffeinate-coffeescript.

fix: don't normalize commas to semicolons outside of block bounds

---

src/utils/normalizeListItem.ts
test/function_call_test.ts
test/object_test.ts
yarn.lock

Follow up from https://github.com/decaffeinate/decaffeinate-parser/pull/273
Adds tests for #1182 and #1191.
Now that implicit object literals have the proper location data, we no longer
need a special case for handling two commas in a row between args, since the
earlier comma is now part of the object literal.

fix: simplify normalizeListItem, add regression tests

---

src/stages/main/patchers/BoundFunctionPatcher.ts
test/function_test.ts
test/soaked_test.ts
yarn.lock

Fixes #1202
add-variable-declarations won't have a place to add a declaration if the
function doesn't have a block body, so if there's any assignment in an arrow
function, we always give it a block body.
The formatting after decaffeinate and add-variable-declarations looks really
bad, I think because add-variable-declarations doesn't attempt to handle inline
functions, but this case is rare enough that I'm not too worried about
formatting.
Also update add-variable-declarations and add a regression test for #1201.

fix: don't generate blockless arrow functions that contain assignments

---

src/stages/main/patchers/BlockPatcher.ts
src/stages/main/patchers/ConditionalPatcher.ts
src/stages/main/patchers/ForPatcher.ts
src/stages/main/patchers/LoopPatcher.ts
src/stages/main/patchers/SwitchPatcher.ts
src/stages/main/patchers/TryPatcher.ts
src/stages/main/patchers/WhilePatcher.ts
src/utils/getEnclosingScopeBlock.ts
test/conditional_test.ts
test/for_test.ts
test/switch_test.ts
test/try_test.ts
test/while_test.ts

Fixes #1205
Previously, the block code had a special case for loop assignees, but we actually
need to hoist all assigned variables when turning a node into an IIFE. We
accomplish this by having all IIFE-capable nodes add themselves to the parent
BlockPatcher, and the BlockPatcher figures out the variable assignees used
outside of the IIFE and explicitly hoists those variables.

fix: handle all assignments within IIFEs

---

.travis.yml

We only want to test against the latest non-stable version. Also, greenkeeperio/greenkeeper-lockfile#98 is fixed so we can revert the switch to npm.

test(ci): replace node v7.x.x with node v9.x.x

---

.travis.yml

Rather than using the `after_success` hook, which runs on all hosts and keeps the first one running until all of them are done, we use the `deploy` hook to run the publishing steps and restrict them to just the `master` branch.

chore(publish): use Travis CI `deploy` configuration

---

src/stages/main/patchers/ProgramPatcher.ts
test/conditional_test.ts

Fixes #1230
Generally with magic-string it's best to patch in order, and to remove before
you add. In this case, we were removing continuation tokens after the fact
across the whole program, which was causing an open-paren to be incorrectly
removed since it was in the range being removed. Removing continuations first
seems to avoid this problem, and also avoid the need to wrap the remove in a
try/catch.

fix: change continuation patching to happen before program patching

---

.github/ISSUE_TEMPLATE/crash.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/wrong.md
README.md

We retain the default one for someone who just stumbles onto the issues page, but if you come from the README we can be a little more targeted.
https://github.com/blog/2495-multiple-issue-and-pull-request-templates

docs(issues): use the new Github multiple issue templates feature

---

src/stages/main/patchers/JavaScriptPatcher.ts
test/javascript_test.ts

Previously I thought escaped backslashes weren't handled at all, but actually
they're only handled just before escaped backticks. That means we need to walk
left whenever we see an escaped backtick, count how many backslashes there are,
and remove the appropriate number to account for escaping.

fix: properly handle escaped backslashes in inline JS

---

src/stages/main/patchers/HeregexPatcher.ts
src/stages/main/patchers/InterpolatedPatcher.ts
src/stages/main/patchers/RegexPatcher.ts
src/utils/downgradeUnicodeCodePointEscapesInRange.ts
src/utils/getCompareOperator.ts
test/regular_expression_test.ts
tsconfig.json

This fixes the last CoffeeScript test failure after upgrading to 1.12.7.
CoffeeScript specifically handles unicode code point escapes in regexes without
the "u" flag specified, e.g. `/\u{a}/`, whereas JavaScript requires the "u" flag
for it to be interpreted as a code point escape. Unfortunately, it's incorrect
to just add the "u" flag, since that introduces various other semantics. To fix,
we just copy CoffeeScript's behavior and downgrade to old-style unicode escapes
in the BMP case and emit old-style unicode escapes for the surrogate pair in the
non-BMP case. When the "u" flag is specified, we skip this behavior.

fix: properly downgrade unicode code point escapes in regexes

---

.travis.yml
package.json
src/index.ts
src/stages/main/patchers/ConditionalPatcher.ts
src/utils/DecaffeinateContext.ts
src/utils/formatCoffeeScriptAst.ts
src/utils/formatCoffeeScriptLexerTokens.ts
src/utils/formatCoffeeScriptLocationData.ts
test/conditional_test.ts
test/for_test.ts
test/function_call_test.ts
test/utils/formatCoffeeScriptAst_test.ts
test/utils/formatCoffeeScriptLexerTokens_test.ts
yarn.lock

This does not yet enable any CS2 features, but sets things up to enable a CS2
mode. There were some minor changes around empty blocks, but that should only
affect formatting.
BREAKING CHANGE: Node 4 is no longer supported.

feat: upgrade decaffeinate-parser to use the CS2 AST format

---

README.md
src/cli.ts
src/stages/main/patchers/SpreadPatcher.ts
test/cli_test.ts
test/spread_test.ts

Progress toward https://github.com/decaffeinate/decaffeinate/issues/427
There's still new syntax and semantics to support, but this gets the beginnings
of a CS2 mode.
For array spread on the left-hand side, we now detect where the ellipsis is and
don't change it if it's already on the left. We also skip Array.from in CS2
mode.

feat: add a `--use-cs2` option and implement LHS array spread

---

.travis.yml

Looks like this got dropped when moving to build stages.

chore: run update-website as part of the release step

---

script/update-website.ts

Looks like this was causing the website to not be updated. With build stages, we
now don't need to do this check.

chore: skip isPrimaryInstance check when updating website

---

src/cli.ts
src/index.ts
src/options.ts
src/utils/formatCoffeeScriptAst.ts
test/utils/formatCoffeeScriptAst_test.ts

* Add support for a `loose` option passed programmatically instead of just
through the CLI.
* Make all intermediate steps specify cs1 or cs2.

feat: update repl-related code to support new repl changes

---

src/stages/main/patchers/AssignOpPatcher.ts
src/stages/main/patchers/ObjectInitialiserPatcher.ts
src/utils/canPatchAssigneeToJavaScript.ts
src/utils/getObjectAssigneeKeys.ts
test/expansion_test.ts

When the object rest is simple and at the end of the object assignment, we can
emit a normal JS object rest. In other situations, we need to emit a helper and
call that helper.

feat: add support for object rest in CS2

---

src/stages/main/index.ts
src/stages/main/patchers/ArrayInitialiserPatcher.ts
src/stages/main/patchers/AssignOpPatcher.ts
src/stages/main/patchers/ElisionPatcher.ts
src/utils/canPatchAssigneeToJavaScript.ts
src/utils/normalizeListItem.ts
test/expansion_test.ts

It looks like add-variable-declarations isn't yet smart enough to place the
`var` in the best place, and we still unnecessarily use `Array.from` in CS2,
but this should be correct.

feat: add basic support for array elisions

---

src/utils/canPatchAssigneeToJavaScript.ts
test/expansion_test.ts

JS object rest appears to only allow assigning to identifiers, but CS allows
complex expressions, so fall back to ugly code if it's anything other than an
identifier.

fix: don't convert complex object rest assignments to JS

---

package.json
src/stages/main/patchers/BlockPatcher.ts
test/function_call_test.ts
yarn.lock

The parser details for blocks surrounded by parens have been tweaked so that the
block bounds include the parens. That means we can't just remove parens
surrounding the block; we need to find interior parens not attached to a child
and remove those. This fixes a test regression from a decaffeinate-parser
change.

fix: remove parens from the inside of a block instead of the outside

---

package.json
script/update-website.ts
src/stages/main/index.ts
src/stages/main/patchers/CSXElementPatcher.ts
src/stages/normalize/patchers/FunctionApplicationPatcher.ts
test/csx_test.ts
test/soaked_test.ts
yarn.lock

This mostly just worked, but there were a few details:
* Strings needed their own case, since CSX allows interpolated strings that
aren't surrounded in curly braces, so we need to sometimes add curly braces.
* For some reason `<div /> arg` (a function call) works and there's a test for
it, but introducing the implicit parens causes a syntax error. To make it not
a syntax error, I wrap the LHS in parens in that one case.
* I had to upgrade esnext in order to support fragment syntax. This ended up
breaking some optional chaining forms that are no longer supported in the
latest proposal, so I disabled those tests.
I also fixed a TypeScript warning in update-website.ts that I ran into when
trying TypeScript configurations.

feat: add CSX patching

---

src/stages/main/patchers/AssignOpPatcher.ts
src/stages/normalize/patchers/ForPatcher.ts
src/stages/normalize/patchers/FunctionPatcher.ts
src/utils/canPatchAssigneeToJavaScript.ts
test/class_test.ts
test/declaration_test.ts
test/expansion_test.ts
test/for_test.ts
test/function_call_test.ts
test/in_test.ts
test/spread_test.ts
test/support/validate.ts

This isn't complete yet, but it gets closer. We now have separate validate
functions for CS1 and CS2 and are able to verify different results for each.
Generally, CS2 shouldn't emit `Array.from` and doesn't need to fall back to
expanded destructures as much.
Some details:
* We now need to be able to patch things like `{@a = 1} = b`, so implement the
patcher for that.
* When patching default values, we may not surround the assignment in parens, so
skip that case.
* When patching default values the expanded way, we need to do `!== undefined`
as the check instead of `!= null`.
* Any `Array.from` in assignment expansion is no longer necessary.
* There are now various differences around what assignment operations we're
willing to patch directly to JS vs expanding.

fix: implement various semantics differences between CS1 and CS2

---

src/utils/postfixNodeNeedsOuterParens.ts
test/spread_test.ts

Fixes #1288
We just wrap in parens to avoid parsing issues with the `...` token.

fix: handle postfix conditionals in spread operators

---

src/stages/main/patchers/ClassAssignOpPatcher.ts
test/class_test.ts

fix: move static keyword before async or * in methods

---

src/stages/normalize/patchers/ClassPatcher.ts
test/class_test.ts

Fixes #1298
The code was deleting from the start of the class declaration, when it should
have been from the end of the `class` token.

fix: properly remove `then` token from anonymous classes

---

src/utils/babelConstructorWorkaroundLines.ts
test/class_test.ts
test/cli_test.ts
test/suggestions_test.ts

This is a fix for: https://github.com/decaffeinate/decaffeinate/issues/1303
I need to test on UglifyJS still and going to do that soon but wanted to get the feedback rolling. I took your suggestion with the validate and adding a test that would exercise the behavior but wasn't sure if you wanted to validate the actual constructor function itself. 
I regexp'd all the other tests to match the new lines as well, since there were a few. 
Queries:
1. Is this what you were thinking?
2. Otherwise, if you were not, did you expect to call `setResult` and verify the result of `thisName` somewhere? If so, how to verify that it ends up in the sandbox? I tried it but ending up getting `thisName` is undefined.

fix: Changed the constructor hack to be more explicit for minifiers

---

.travis.yml

Test in the latest (v11) and all currently supported LTS versions. Node v6 is supported until April 2019, so we can remove it after that.

test(ci): update node versions to test with

---

src/options.ts

This fixes backward-incompatibility that would have required a major version bump.

fix: allow "EsnextStage" as an alias for "ResugarStage"

---

package.json
yarn.lock

This removes `typescript-eslint-parser` because it was replaced by `@typescript-eslint/parser` and should have been removed when that one was added.

build(dev-deps): update eslint typescript packages

---

src/stages/main/patchers/ForInPatcher.ts
src/utils/countVariableUsages.ts
test/for_test.ts
test/utils/countVariableUsages_test.ts

The particular case that identified this issue is from #1483, in which `r.a` was being considered a usage of the `a` variable. This case and a few others are fixed in this commit.

fix: more correctly identify variable usages

---

src/utils/DecaffeinateContext.ts
test/function_test.ts

Without this, async functions could not be the target for variable hoisting.
Fixes #1506

fix: ensure `AsyncFunction` gets its own scope

---

.eslintrc.js
package.json
test/function_test.ts
yarn.lock

I accidentally commited and merged to master an `it.only` exclusive mocha test. This has happened several times and I finally got sick of it. Now we fail the build if I forget one!

chore: ensure exclusive tests can't sneak in again

---

package.json
yarn.lock

This package was being published with `.ts` files, which causes problems with TypeScript 3.7. It's since been fixed in v1.0.2.

chore(deps): update codemod-objects-concise

---

script/build

`npm pack` seems to use nested `package.json` when deciding what to pack. This wasn't there before, but one of the upgrades, likely TypeScript, now copies over the `package.json` file. Removing it restores packing behavior to what it was before.

fix(package): include all desired files

---

README.md

I wrote a blog post about how Dropbox got rid of coffeescript using decaffeinate.  Thanks for the awesome tool that made that possible!

add a link to the Dropbox blog post

---

src/stages/main/patchers/ClassBlockPatcher.ts
test/class_test.ts
test/suggestions_test.ts

CS2 changed the behavior of when classes would bind methods to be compatible with ES6 classes. They bind after the call to super, rather than before as in CS1. When targeting CS2, follow that same behavior.
Refs https://github.com/decaffeinate/decaffeinate/issues/2141.

fix: bind after super call in CS2

---

src/stages/main/patchers/ClassBlockPatcher.ts
test/class_test.ts

Annoyingly, TypeScript didn't catch this because adding non-string things to a string is allowed since they get coerced to a string. For arrays, it calls `join()` on the array which by default joins with a comma. With a single binding this happened to work, but it breaks with multiple bindings.
Closes #2169

fix(class): ensure multiple bindings work in generated constructor

---

package.json
yarn.lock

Without this, I get `__spreadArray is not a function` loading decaffeinate on the website REPL. It seems this helper was added in v2.1.0, and something is expecting it to be there (`tsc`?). I think this will fix it.

fix: upgrade `tslib` to v2.1.0

---

src/stages/resugar/index.ts

Should fix #1622. Basically `codemod.transform` directly calls `babel.transformSync`, and babel [will pick up](https://babeljs.io/docs/en/options#configfile) `babel.config.json` by default. We don't actually care how the target repo compiles its code, we're only resugaring the code that's been converted, so just forcing babel to not look up any config fixes the issue.
Fixed this with patch-package on our work repo, takes 100+ compile errors down to zero.
```patch
diff --git a/node_modules/decaffeinate/dist/stages/resugar/index.js b/node_modules/decaffeinate/dist/stages/resugar/index.js
--- a/node_modules/decaffeinate/dist/stages/resugar/index.js
+++ b/node_modules/decaffeinate/dist/stages/resugar/index.js
@@ -19,6 +19,8 @@ var ResugarStage = /** @class */ (function () {
log(content);
var …
```

Make codemod transform ignore babel config, babelrc

---

src/utils/normalizeListItem.ts
test/object_test.ts

Fixes #2413
When there was an implicit object as the sole argument to a nested function application that ended with a trailing comma, the normalize stage would fail to generate corect CoffeeScript. The normalize stage would insert the opening and closing parentheses, but also attempt to remove the trailing comma as it was "unnecessary". Normally this doesn't cause a problem because the comma is removed and then the closing parenthesis is added after it. However, because there are two nested function applications, we end up with these operations:
1. insert opening parenthesis for outer function application
2. remove comma after last argument of inner function appliication
3. insert opening parenthesis for inner function application
4. remove same comma again for outer function application, …

fix: account for trailing commas in nested calls

---

README.md
src/cli.ts

We had `--use-optional-chaining`, but that was disabled in #1338. This commit makes it an alias for `--optional-chaining`, which was added in #1969. Also adds `--logical-assignment` to the CLI help.

fix(cli): update newer flags

---

.circleci/config.yml

Tests with 14, 16, and 17. 10 and 12 are both EOL.

ci: update Node versions

---

.circleci/config.yml

`cimg/node` doesn't have a `latest` tag, only `lts`.

ci: use correct tag for deploy job

---

.circleci/config.yml
package.json

We don't need to rebuild after every `yarn add`.

chore: use `prepublishOnly`

---

bin/decaffeinate

This was broken by 4c507bda29bc21b053c4cd71c966e96e48c72d63 starting in v7.0.0.

fix(cli): pass the correct args

---

package.json
yarn.lock

v3.0.0 and v3.0.1 had issues with import vs require: https://github.com/eventualbuddha/automatic-semicolon-insertion/pull/34.

fix(deps): require at least `automatic-semicolon-insertion@3.0.2`

---

src/stages/main/patchers/ConstructorPatcher.ts
src/stages/normalize/patchers/ConstructorPatcher.ts
src/stages/normalize/patchers/FunctionPatcher.ts
test/class_test.ts

CoffeeScript 2 puts autogenerated `this` assignments after the call to the `super`-constructor.
For example, in this code:
```coffee
class A extends B
constructor: (@a) ->
super()
f: =>
```
The assignments to `this.a` and `this.f` are generated just after `super()`.
This commit ensures that decaffeinate follows the same rule.

fix: place this assignments after super under CS2

---

package.json
pnpm-lock.yaml
test/mocha.opts

We can just use `esr` from `esbuild-runner`.

chore(deps): remove `ts-node`

---

.github/workflows/ci.yml
docs/contribution-guide.md
package.json

Allows declaring the version of the package manager being used in the project in `packageManager` within `package.json`.

chore: enable `corepack`

---

src/cli.ts
src/index.ts
src/options.ts
test/cli_test.ts
test/iife_test.ts
test/support/check.ts

Adds `bare` option, which is `true` by default, but when `false` will wrap the output in an IIFE similar to the official CoffeeScript compiler's default behavior. This can be triggered on the CLI with `--no-bare`, which mirrors `coffee`'s `--bare` flag.
**Example:**
```sh
❯ echo 'a = 1' | decaffeinate --no-bare
(function() {
const a = 1;
}).call(this);                                                                                                           
```
Closes #2412

feat: add `bare` option to allow IIFE wrapper

---

src/cli.ts
src/index.ts
test/cli_test.ts

I don't see why this would be useful, but might as well allow it. Per https://github.com/decaffeinate/decaffeinate/pull/2481#discussion_r917463444.

fix: allow `--modernize-js` with `--no-bare`

---

src/cli.ts
test/cli_test.ts

Tools like `bulk-decaffeinate` rely on errors to determine when it is safe to run `decaffeinate`.
Currently, running `decaffeinate --disallow-invalid-constructors` exits with code 0 instead of code 1, which leads `bulk-decaffeinate` to believe no errors were encountered in the "check" run.
This change makes it instead exit with code 1, which results in the correct behavior in `bulk-decaffeinate`.

Exit with code 1 when the patcher fails

---

package.json
pnpm-lock.yaml
tsconfig.json

Updates `@typescript-eslint/*` too. Skips lib check due to a `WebAssembly` error in `esbuild`.

chore(dev-deps): update typescript

---

.eslintignore
package.json
script/update-website

Instead of calling `esr` from the CLI, wrap the `.ts` file with an executable that installs `esbuild-runner`'s `require` hooks.

chore(script): make `update-website` executable

---

src/patchers/NodePatcher.ts
src/stages/main/patchers/BinaryOpPatcher.ts
src/stages/main/patchers/BlockPatcher.ts
src/stages/main/patchers/ChainedComparisonOpPatcher.ts
src/stages/main/patchers/ClassPatcher.ts
src/stages/main/patchers/ConditionalPatcher.ts
src/stages/main/patchers/DoOpPatcher.ts
src/stages/main/patchers/EqualityPatcher.ts
src/stages/main/patchers/LogicalOpCompoundAssignOpPatcher.ts
src/stages/main/patchers/LogicalOpPatcher.ts
src/stages/main/patchers/LoopPatcher.ts
src/stages/main/patchers/ObjectInitialiserMemberPatcher.ts
src/stages/main/patchers/ObjectInitialiserPatcher.ts
src/stages/main/patchers/ProgramPatcher.ts
src/stages/main/patchers/RangePatcher.ts
src/stages/main/patchers/SlicePatcher.ts
src/stages/main/patchers/SuperPatcher.ts
src/stages/main/patchers/SwitchCasePatcher.ts
src/stages/main/patchers/SwitchPatcher.ts
src/stages/main/patchers/TryPatcher.ts
src/stages/main/patchers/UnaryExistsOpPatcher.ts
src/stages/main/patchers/WhilePatcher.ts
src/stages/normalize/patchers/ForPatcher.ts
src/stages/normalize/patchers/WhilePatcher.ts
src/utils/Scope.ts

Anything that was marked `@private` but actually needed to be public or protected I updated manually.

refactor: mark private methods as such

---

package.json
pnpm-lock.yaml

Switch from pnpm7 to pnpm8, seeing as pnpm9 is the most recent release. This is accurate to what versions of pnpm are fresh in package managers other than npm, such as nixpkgs.
Switch from lockfile v5.4 to v6.0 for compatibility with pnpm8. v5 is recently deprecated, and causes an error when freezing the lockfile for pnpm8 and above.

Bump pnpm and pnpm-lock Version

---

docs/conversion-guide.md

Link to cleanup suggestions was actually linking to the `How decaffeinate approaches correctness` page

Fix incorrect link in docs

---

.github/workflows/ci.yml
.github/workflows/release.yml

Keeping v16 for now, but will probably get rid of it as part of the next update.

ci: update NodeJS versions
